### ISSUE TITLE
Errors in test run after ch 8

### ISSUE THREAD

**Issue by tnovak123** [miguelgrinberg/microblog#100]
hi miguel,
i made it through to chapter 8. I ran the tests that you had us put into the code but i am getting back 4 errors, which are as follows:
ERROR: test_avatar (__main__.UserModelCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\interfaces.py", line 509, in _get_strategy
    return self._strategies[key]
KeyError: (('lazy', 'dymanic'),)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests.py", line 22, in test_avatar
    u = User(username='john', email='john@example.com')
  File "<string>", line 2, in __init__
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 391, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 767, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 221, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\event\attr.py", line 284, in __call__
    fn(*args, **kw)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\mapper.py", line 3139, in _event_on_first_init
    configure_mappers()
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\mapper.py", line 3029, in configure_mappers
    mapper._post_configure_properties()
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\mapper.py", line 1828, in _post_configure_properties
    prop.init()
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\interfaces.py", line 184, in init
    self.do_init()
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    super(RelationshipProperty, self).do_init()
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\interfaces.py", line 539, in do_init
    self.strategy = self._get_strategy(self.strategy_key)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\interfaces.py", line 511, in _get_strategy
    cls = self._strategy_lookup(*key)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\interfaces.py", line 570, in _strategy_lookup
    raise Exception("can't locate strategy for %s %s" % (cls, key))
Exception: can't locate strategy for <class 'sqlalchemy.orm.relationships.RelationshipProperty'> (('lazy', 'dymanic'),)

======================================================================
ERROR: test_follow (__main__.UserModelCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 26, in test_follow
    u1 = User(username='john', email='john@example.com')
  File "<string>", line 2, in __init__
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 391, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 767, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 221, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\event\attr.py", line 284, in __call__
    fn(*args, **kw)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\mapper.py", line 3139, in _event_on_first_init
    configure_mappers()
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\mapper.py", line 3026, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper|User|user'
. Original exception was: can't locate strategy for <class 'sqlalchemy.orm.relationships.RelationshipProperty'> (('lazy', 'dymanic'),)

======================================================================
ERROR: test_follow_posts (__main__.UserModelCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 48, in test_follow_posts
    u1 = User(username='john', email='john@example.com')
  File "<string>", line 2, in __init__
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 391, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 767, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 221, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\event\attr.py", line 284, in __call__
    fn(*args, **kw)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\mapper.py", line 3139, in _event_on_first_init
    configure_mappers()
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\mapper.py", line 3026, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper|User|user'
. Original exception was: can't locate strategy for <class 'sqlalchemy.orm.relationships.RelationshipProperty'> (('lazy', 'dymanic'),)

======================================================================
ERROR: test_password_hashing (__main__.UserModelCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 16, in test_password_hashing
    u = User(username='susan')
  File "<string>", line 2, in __init__
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 391, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 767, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\instrumentation.py", line 221, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\event\attr.py", line 284, in __call__
    fn(*args, **kw)
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\mapper.py", line 3139, in _event_on_first_init
    configure_mappers()
  File "C:\Users\Marla\AppData\Local\conda\conda\envs\flask-env\lib\site-packages\sqlalchemy\orm\mapper.py", line 3026, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper|User|user'
. Original exception was: can't locate strategy for <class 'sqlalchemy.orm.relationships.RelationshipProperty'> (('lazy', 'dymanic'),)
-----
I am having difficulty understanding where to find the places in the code where these errors are located, and as a result, I am having difficulty solving them on my own.

I have checked many different files to make sure that my code is the same as your code. i have checked models.py which is exact, __init__.py = exact, and several others. Can you help me understand the error messages, and also find the solutions?

**Comment by miguelgrinberg** [comment]
You have a typo. Instead of `dymanic`, you have to use `dynamic`.

**Comment by tnovak123** [comment]
thank you so much. I looked at it so many times and i didn't even see it.

**Comment by tnovak123** [comment]
here are some new errors...lol
FAIL: test_avatar (__main__.UserModelCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 23, in test_avatar
    self.assertEqual(u.avatar(128), ('
https://www.gravatar.com/avatar/d4c74594d841139328695756648b6bd6?d=identicon&s=128
'))
AssertionError: 'http[17 chars]com/avatar/d4c74594d841139328695756648b6bd6?
d=identicon&s=128' != 'http[17 chars]com/ava
tar/d4c74594d841139328695756648b6bd6?d=identicon&s=128'
- https://www.gravatar.com/avatar/d4c74594d841139328695756648b6bd6?
d=identicon&s=128
?                                                                  -
+
https://www.gravatar.com/avatar/d4c74594d841139328695756648b6bd6?d=identicon&s=128


======================================================================
FAIL: test_follow_posts (__main__.UserModelCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 75, in test_follow_posts
    self.assertEqual(f1, [p2, p3])
AssertionError: Lists differ: [<Post  post from susan>, <Post  post from
david>, <Post  post from john>] != [<Post  post
 from susan>, <Post  post from mary>]

First differing element 1:
<Post  post from david>
<Post  post from mary>

First list contains 1 additional elements.
First extra element 2:
<Post  post from john>

- [<Post  post from susan>, <Post  post from david>, <Post  post from john>]
?                                            ^ ------------------- ^^^^^^^

+ [<Post  post from susan>, <Post  post from mary>]
?                                            ^  ^

**Comment by tnovak123** [comment]
i figured out the error about the posting. it's the avatar error that i
need help with.

**Comment by miguelgrinberg** [comment]
I can't really tell you what the problem is with the avatar, it seems the avatar URL got cut in the middle with a new line in the middle, but I'm not sure. You are supposed to debug these errors yourself. You have my code to help you.

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Seeing that I haven't responded to your last comment, it is quite possible that I have dropped the ball on this issue and I apologize about that. If that is the case, do not take the closing of the issue personally as it is an automated process doing it, just reopen it and I'll get back to you.
