### ISSUE TITLE
TypeError: unsupported operand types(s) or combination of types: 'dict' and 'dict'

### ISSUE THREAD

**Issue by Linxd2015** [miguelgrinberg/microblog#101]
Hi miguel,
I used windows + python 3.5 +Flask 0.10 . I clicked the 'Sign In' without any data on the login page,  but i am getting back the error,which are as follows:
Traceback (most recent call last):
  File "E:\microblog\venv\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\microblog\venv\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "E:\microblog\venv\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\microblog\venv\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\microblog\venv\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\microblog\venv\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\microblog\venv\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\microblog\venv\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\microblog\app\routes.py", line 26, in login
    if form.validate_on_submit():
  File "E:\microblog\venv\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "E:\microblog\venv\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "E:\microblog\venv\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "E:\microblog\venv\lib\site-packages\wtforms\fields\core.py", line 193, in validate
    self.pre_validate(form)
  File "E:\microblog\venv\lib\site-packages\wtforms\csrf\core.py", line 39, in pre_validate
    self.csrf_impl.validate_csrf_token(form, self)
  File "E:\microblog\venv\lib\site-packages\flask_wtf\csrf.py", line 147, in validate_csrf_token
    self.meta.csrf_field_name
  File "E:\microblog\venv\lib\site-packages\flask_wtf\csrf.py", line 98, in validate_csrf
    if not safe_str_cmp(session[field_name], token):
  File "E:\microblog\venv\lib\site-packages\werkzeug\security.py", line 138, in safe_str_cmp
    return _builtin_safe_str_cmp(a, b)
TypeError: unsupported operand types(s) or combination of types: 'dict' and 'dict'

Hope to get you help，thanks

**Comment by miguelgrinberg** [comment]
Do you get a different result if you type some data in the form?

**Comment by Linxd2015** [comment]
I used the code of chapter 3 and tried different data. This error occurs when username is empty. No error after using the same software version as another mac computer。

**Comment by miguelgrinberg** [comment]
Sorry, but I don't quite follow what you are saying. The error does not happen on a different computer? What do you mean by first and second case?

**Comment by Linxd2015** [comment]
I'm sorry, I didn't make it clear enough.The error does not happen on a different computer.I mean I try to submit an empty account and password will get the error
