### ISSUE TITLE
JSON serializable error while running the code

### ISSUE THREAD

**Issue by prabhupant** [miguelgrinberg/microblog#103]
**I am getting while running the final code after chapter 5**

[2018-05-06 10:35:27,636] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prabhu/Desktop/microblog/app/routes.py", line 30, in login
    form = LoginForm()
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/flask_wtf/csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "/home/prabhu/Desktop/microblog/venv/lib/python3.5/site-packages/itsdangerous.py", line 51, in dumps
    return json.dumps(obj, separators=(',', ':'))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'8fc9e0cdf61f76b42b310318a2652d32af07f556' is not JSON serializable
127.0.0.1 - - [06/May/2018 10:35:27] "GET /login?next=%2F HTTP/1.1" 500 -

I'm on Ubuntu 16.04. I also tried running your code in case mine had some bugs or typos but still the same result.

**Comment by miguelgrinberg** [comment]
Any chance you may have an old session cookie still in your browser from another Flask application? Try using an incognito or private browsing window, if that works, then it is likely you have a stale session cookie in your browser.

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Please reopen if you need more assistance.
