### ISSUE TITLE
Error running test.py (Unittests)

### ISSUE THREAD

**Issue by zo1d** [miguelgrinberg/microblog#104]
Hello, 

I have a problem running test.py (unittest) after The Flask Mega-Tutorial Part XV: A Better Application Structure chapter.  Here is the problem:

```
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$ python tests.py
Traceback (most recent call last):
  File "tests.py", line 4, in <module>
    from app import create_app, db
  File "/home/dusty/Code/Sites/HackerHub/app/__init__.py", line 4, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named 'flask_sqlalchemy'
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$
```

```
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$ cat tests.py
#!/usr/bin/env python
from datetime import datetime, timedelta
import unittest
from app import create_app, db
from app.models import User, Post
from config import Config


class TestConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = 'sqlite://'


class UserModelCase(unittest.TestCase):
    def setUp(self):
        self.app = create_app(TestConfig)
        self.app_context = self.app.app_context()
        self.app_context.push()
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()
        self.app_context.pop()

    def test_password_hashing(self):
        u = User(username='susan')
        u.set_password('cat')
        self.assertFalse(u.check_password('dog'))
        self.assertTrue(u.check_password('cat'))

    def test_avatar(self):
        u = User(username='john', email='john@example.com')
        self.assertEqual(u.avatar(128), ('https://www.gravatar.com/avatar/'
                                         'd4c74594d841139328695756648b6bd6'
                                         '?d=identicon&s=128'))

    def test_follow(self):
        u1 = User(username='john', email='john@example.com')
        u2 = User(username='susan', email='susan@example.com')
        db.session.add(u1)
        db.session.add(u2)
        db.session.commit()
        self.assertEqual(u1.followed.all(), [])
        self.assertEqual(u1.followers.all(), [])

        u1.follow(u2)
        db.session.commit()
        self.assertTrue(u1.is_following(u2))
        self.assertEqual(u1.followed.count(), 1)
        self.assertEqual(u1.followed.first().username, 'susan')
        self.assertEqual(u2.followers.count(), 1)
        self.assertEqual(u2.followers.first().username, 'john')

        u1.unfollow(u2)
        db.session.commit()
        self.assertFalse(u1.is_following(u2))
        self.assertEqual(u1.followed.count(), 0)
        self.assertEqual(u2.followers.count(), 0)

    def test_follow_posts(self):
        # create four users
        u1 = User(username='john', email='john@example.com')
        u2 = User(username='susan', email='susan@example.com')
        u3 = User(username='mary', email='mary@example.com')
        u4 = User(username='david', email='david@example.com')
        db.session.add_all([u1, u2, u3, u4])

        # create four posts
        now = datetime.utcnow()
        p1 = Post(body="post from john", author=u1,
                  timestamp=now + timedelta(seconds=1))
        p2 = Post(body="post from susan", author=u2,
                  timestamp=now + timedelta(seconds=4))
        p3 = Post(body="post from mary", author=u3,
                  timestamp=now + timedelta(seconds=3))
        p4 = Post(body="post from david", author=u4,
                  timestamp=now + timedelta(seconds=2))
        db.session.add_all([p1, p2, p3, p4])
        db.session.commit()

        # setup the followers
        u1.follow(u2)  # john follows susan
        u1.follow(u4)  # john follows david
        u2.follow(u3)  # susan follows mary
        u3.follow(u4)  # mary follows david
        db.session.commit()

        # check the followed posts of each user
        f1 = u1.followed_posts().all()
        f2 = u2.followed_posts().all()
        f3 = u3.followed_posts().all()
        f4 = u4.followed_posts().all()
        self.assertEqual(f1, [p2, p4, p1])
        self.assertEqual(f2, [p2, p3])
        self.assertEqual(f3, [p3, p4])
        self.assertEqual(f4, [p4])


if __name__ == '__main__':
    unittest.main(verbosity=2)
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$
```

```
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$ cat app/__init__.py
import logging, os
from logging.handlers import SMTPHandler, RotatingFileHandler

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_babel import Babel, lazy_gettext as _l
from config import Config
from flask import Flask, request, current_app

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = _l('Please log in to access this page')
mail = Mail()
bootstrap = Bootstrap()
moment = Moment()
babel = Babel()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate = Migrate(app, db)
    login.init_app(app)
    mail.init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    babel.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug and not app.testing:
        if app.config['MAIL_SERVER']:
            auth = None
            if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:
                auth = (app.config['MAIL_USERNAME'], app.config['MAIL_PASSWORD'])
            secure = None
            if app.config['MAIL_USE_TLS']:
                secure = ()
            mail_handler = SMTPHandler(
                mailhost = (app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                fromaddr = 'no-reply@' + app.config['MAIL_SERVER'],
                toaddrs  = app.config['ADMINS'], subject='HackerHub Failure',
                credentials = auth, secure=secure)
            mail_handler.setLevel(logging.ERROR)
            app.logger.addHandler(mail_handler)

        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/hackerhub.log', maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)s]'
            ))
        file_handler.setLevel(logging.ERROR)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.ERROR)
        app.logger.info('HackerHub Startup')

    return app

@babel.localeselector
def get_locale():
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
    #return 'es'



from app import models
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$
```

```
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$ pwd
/home/dusty/Code/Sites/HackerHub
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$ ls -l
total 64
drwxrwxr-x 9 dusty dusty  4096 May  9 02:24 app
-rw-r--r-- 1 dusty dusty 11264 May  9 00:23 app.db
-rw-rw-r-- 1 dusty dusty   103 May  6 22:02 babel.cfg
-rw-rw-r-- 1 dusty dusty   138 May  8 23:14 BAK.env
-rw-rw-r-- 1 dusty dusty   956 May  9 00:28 config.py
-rw-rw-r-- 1 dusty dusty   217 May  8 23:40 hackerhub.py
drwxrwxr-x 2 dusty dusty  4096 May  8 23:59 logs
-rwxrwxr-x 1 dusty dusty    64 May  8 21:01 mail_srv.sh
drwxrwxr-x 4 dusty dusty  4096 May  8 23:57 migrations
drwxrwxr-x 2 dusty dusty  4096 May  9 00:28 __pycache__
-rw-rw-r-- 1 dusty dusty   598 May  8 23:14 requirements.txt
-rw-rw-r-- 1 dusty dusty   333 May  1 17:12 run.sh
-rwxr-xr-x 1 dusty dusty  3513 May  9 02:21 tests.py
drwxrwxr-x 6 dusty dusty  4096 Apr 15 20:03 venv
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$ ls -l app
total 48
drwxrwxr-x 3 dusty dusty 4096 May  8 23:52 auth
-rw-rw-r-- 1 dusty dusty 1149 May  8 23:40 cli.py
-rw-rw-r-- 1 dusty dusty  476 May  9 02:24 email.py
drwxrwxr-x 3 dusty dusty 4096 May  8 23:34 errors
-rw-rw-r-- 1 dusty dusty 2625 May  9 02:20 __init__.py
drwxrwxr-x 3 dusty dusty 4096 May  9 00:19 main
-rw-rw-r-- 1 dusty dusty 3112 May  8 23:17 models.py
drwxrwxr-x 2 dusty dusty 4096 May  9 02:27 __pycache__
drwxrwxr-x 2 dusty dusty 4096 May  8 03:01 static
drwxrwxr-x 5 dusty dusty 4096 May  9 00:15 templates
-rw-rw-r-- 1 dusty dusty 1207 May  8 23:25 translate.py
drwxrwxr-x 3 dusty dusty 4096 May  6 22:41 translations
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$
```

I cannot seem to figure out what is causing this? it appears all the imports from app/__init__.py when you run test.py and it executes: from app import create_app, db.. 

Thank you in advance.

**Comment by zo1d** [comment]
Ok so it appears to be an issue with my virtual environment, although I am not sure why:

```
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$ which python
/home/dusty/Code/Sites/HackerHub/venv/bin/python
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$ python tests.py
Traceback (most recent call last):
  File "tests.py", line 7, in <module>
    from app.models import User
  File "/home/dusty/Code/Sites/HackerHub/app/__init__.py", line 4, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named 'flask_sqlalchemy'
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$ ./venv/bin/python tests.py
test_avatar (__main__.UserModelCase) ... ok
test_follow (__main__.UserModelCase) ... ok
test_follow_posts (__main__.UserModelCase) ... ok
test_password_hashing (__main__.UserModelCase) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.236s

OK
(venv) dusty@core-appserver-01:~/Code/Sites/HackerHub$
```

Why does it fail with "python tests.py" even though that python is linked to venv/bin/python?

**Comment by miguelgrinberg** [comment]
Just saw this on SO and responded there. I have actually never seen this problem, I have no idea what is wrong in your virtualenv. I suggest you make a new virtualenv to see if you can repeat the problem or not.

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Please reopen if you need more assistance.
