### ISSUE TITLE
AttributeError: 'function' object has no attribute 'id'

### ISSUE THREAD

**Issue by JacobCover** [miguelgrinberg/microblog#118]
When I try to unfollow a user, I get the error `AttributeError: 'function' object has no attribute 'id'` referencing the following code:
```    
def is_following(self, user):
        return self.followed.filter(
            followers.c.followed_id == user.id).count() > 0 
```

I am on part 15 but have skipped parts 13 and 14 to get the restructuring done. I am not sure where to go based on this error, please help if you can!
Thanks, 
J Cover

*Full traceback:*
```
Traceback (most recent call last):
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\users\jdc10\documents\github\flasktest\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\Users\jdc10\Documents\GitHub\FlaskTest\app\main\routes.py", line 132, in unfollow
    current_user.unfollow(user)
  File "D:\Users\jdc10\Documents\GitHub\FlaskTest\app\models.py", line 51, in unfollow
    if self.is_following(user):
  File "D:\Users\jdc10\Documents\GitHub\FlaskTest\app\models.py", line 56, in is_following
    followers.c.followed_id == user.id).count() > 0
AttributeError: 'function' object has no attribute 'id'
```

*My models.py file:*
```
from app import db, login
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash
from hashlib import md5
from time import time
import jwt
from flask import current_app


followers = db.Table(
    'followers',
    db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('followed_id', db.Integer, db.ForeignKey('user.id'))
)


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    followed = db.relationship(
        'User', secondary=followers,
        primaryjoin=(followers.c.follower_id == id),
        secondaryjoin=(followers.c.followed_id == id),
        backref=db.backref('followers', lazy='dynamic'), lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, size)

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def is_following(self, user):
        return self.followed.filter(
            followers.c.followed_id == user.id).count() > 0

    def followed_posts(self):
        followed = Post.query.join(
            followers, (followers.c.followed_id == Post.user_id)).filter(
            followers.c.follower_id == self.id)
        own = Post.query.filter_by(user_id=self.id)
        return followed.union(own).order_by(Post.timestamp.desc())

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expires_in},
            current_app.config['SECRET_KEY'],
            algorithm='HS256').decode('utf-8')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config['SECRET_KEY'], algorithm='HS256')['reset_password']
        except:
            return
        return User.query.get(id)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    def __repr__(self):
        return '<Post: {}>'.format(self.body)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))
```

**Comment by miguelgrinberg** [comment]
How does your `unfollow()` function in routes.py look?

**Comment by JacobCover** [comment]
It is as follows: 

```
@bp.route('/unfollow/<username>')
@login_required
def unfollow(username):
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are no longer following {}.'.format(username))
    return redirect(url_for('main.user', username=username))
```

**Comment by JacobCover** [comment]
Great, thanks!
