### ISSUE TITLE
Chapters 17-19: Consistent errors with the followers database

### ISSUE THREAD

**Issue by JacobCover** [miguelgrinberg/microblog#120]
Hey again, 
I have tried all 3 deployment methods in the hopes that one will use a different SQL implementation that will avoid the error I have been having but no such luck. Each time, on a remote linux server, on heroku, and in docker, the site returns the following error after I successfully create an account, login, then hit the error when I am redirected to index:
```
Traceback (most recent call last):
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'microblog.followers' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/royalcows9/FlaskTest/app/main/routes.py", line 32, in index
    posts = current_user.followed_posts().paginate(page, current_app.config['POSTS_PER_PAGE'], False)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 491, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2836, in all
    return list(self)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/royalcows9/FlaskTest/venv/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)

sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'microblog.followers' doesn't exist") [SQL: 'SELECT anon_1.post_id AS anon_1_post_id, anon_1.post_body AS anon_1_post_body, anon_1.post_timestamp AS anon_1_post_timestamp, anon_1.post_user_id AS anon_1_post_user_id \nFROM (SELECT post.id AS post_id, post.body AS post_body, post.timestamp AS post_timestamp, post.user_id AS post_user_id \nFROM post INNER JOIN followers ON followers.followed_id = post.user_id \nWHERE followers.follower_id = %(follower_id_1)s UNION SELECT post.id AS post_id, post.body AS post_body, post.timestamp AS post_timestamp, post.user_id AS post_user_id \nFROM post \nWHERE post.user_id = %(user_id_1)s) AS anon_1 ORDER BY anon_1.post_timestamp DESC \n LIMIT %(param_1)s, %(param_2)s'] [parameters: {'param_1': 0, 'param_2': 7, 'follower_id_1': 1, 'user_id_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)
```
Seems to be that the followers database doesn't exist, but that shouldn't be the case. When I open app.db up witha database explorer, the followers table exists just fine! Please help!!

*My models.py*
```
from app import db, login
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash
from hashlib import md5
from time import time
import jwt
from flask import current_app


followers = db.Table(
    'followers',
    db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('followed_id', db.Integer, db.ForeignKey('user.id'))
)


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    followed = db.relationship(
        'User', secondary=followers,
        primaryjoin=(followers.c.follower_id == id),
        secondaryjoin=(followers.c.followed_id == id),
        backref=db.backref('followers', lazy='dynamic'), lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, size)

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def is_following(self, user):
        return self.followed.filter(
            followers.c.followed_id == user.id).count() > 0

    def followed_posts(self):
        followed = Post.query.join(
            followers, (followers.c.followed_id == Post.user_id)).filter(
            followers.c.follower_id == self.id)
        own = Post.query.filter_by(user_id=self.id)
        return followed.union(own).order_by(Post.timestamp.desc())

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expires_in},
            current_app.config['SECRET_KEY'],
            algorithm='HS256').decode('utf-8')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config['SECRET_KEY'], algorithm='HS256')['reset_password']
        except:
            return
        return User.query.get(id)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    def __repr__(self):
        return '<Post: {}>'.format(self.body)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

```

**Comment by miguelgrinberg** [comment]
Did you check your migration scripts? Is there a `followers` table there?

**Comment by JacobCover** [comment]
Huh. The migration seems very behind, not sure why. There is no followers table there, but somehow the SQLite app.db file does have a followers table. What do I need to do to get the migration to update?


Here is the one and only migration file:
```
"""empty message
Revision ID: 120cd66f7b01
Revises: 
Create Date: 2018-08-03 03:50:47.304044
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120cd66f7b01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('test_column', sa.String(length=1), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
```

**Comment by JacobCover** [comment]
Any ideas? I'm thinking that it can't find the models.py file for some reason but have no idea how to fix that.

**Comment by miguelgrinberg** [comment]
The `flask db migrate` output indicates you are using MySQL, yet you are said you checked a SQLite database for the `followers` table. My guess is that the problems are a result of mixing up two or more databases.

**Comment by JacobCover** [comment]
Hmm. I want to use MySQL on my deployment, I just loaded up the SQLite database because it was something I could check. What's weird is that this has happened in Docker, Heroku, and on a Google Cloud Compute machine. I deleted the migrations folder and re-ran `flask db init`, then `flask db migrate` and no new version was created. Why would this not happen?

**Comment by JacobCover** [comment]
Just tested `flask db migrate` on my desktop that I thought was working, it also doesn't create new versions when changes are made to models.py. I'm in over my head here, maybe I can just make the table with SQL commands? Not really sure what to do.

**Comment by miguelgrinberg** [comment]
I can't really tell you what's wrong, because this is likely some small mistake. When Alembic doesn't generate any changes it can be one of two things: either the models are not being imported (so Alembic does not know about them), or the database tables match the model definition, so Alembic decides there is nothing to migrate.

**Comment by miguelgrinberg** [comment]
Closing due to inactivity.
