### ISSUE TITLE
Chapter 4 SQL Alchemy NoSuchModuleError

### ISSUE THREAD

**Issue by Siddapa** [miguelgrinberg/microblog#126]
I know that this error has been addressed before, but when I run the :

**flask db migrate -m "users table"** 

command. It returns this error:

**sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqlit**

If you notice with this error that the module name isn't "sqlite", it's "sqlit" with no 'E'. After going through the packages, I found that I do indeed have the package for sqlite to work, but not sqlit. Does anyone know why SQL Alchemy is looking for this specific package?

**Comment by Siddapa** [comment]
(venv) C:\Users\T41765\microblog>flask db migrate -m "users table"
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\T41765\microblog\venv\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\users\t41765\microblog\venv\lib\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "c:\users\t41765\microblog\venv\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\t41765\microblog\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\t41765\microblog\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\t41765\microblog\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\t41765\microblog\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\t41765\microblog\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\t41765\microblog\venv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\t41765\microblog\venv\lib\site-packages\flask\cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\users\t41765\microblog\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\t41765\microblog\venv\lib\site-packages\flask_migrate\cli.py", line 90, in migrate
    rev_id, x_arg)
  File "c:\users\t41765\microblog\venv\lib\site-packages\flask_migrate\__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "c:\users\t41765\microblog\venv\lib\site-packages\flask_migrate\__init__.py", line 215, in migrate
    version_path=version_path, rev_id=rev_id)
  File "c:\users\t41765\microblog\venv\lib\site-packages\alembic\command.py", line 176, in revision
    script_directory.run_env()
  File "c:\users\t41765\microblog\venv\lib\site-packages\alembic\script\base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "c:\users\t41765\microblog\venv\lib\site-packages\alembic\util\pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\users\t41765\microblog\venv\lib\site-packages\alembic\util\compat.py", line 82, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations\env.py", line 87, in <module>
    run_migrations_online()
  File "migrations\env.py", line 70, in run_migrations_online
    poolclass=pool.NullPool)
  File "c:\users\t41765\microblog\venv\lib\site-packages\sqlalchemy\engine\__init__.py", line 466, in engine_from_config
    return create_engine(url, **options)
  File "c:\users\t41765\microblog\venv\lib\site-packages\sqlalchemy\engine\__init__.py", line 425, in create_engine
    return strategy.create(*args, **kwargs)
  File "c:\users\t41765\microblog\venv\lib\site-packages\sqlalchemy\engine\strategies.py", line 57, in create
    entrypoint = u._get_entrypoint()
  File "c:\users\t41765\microblog\venv\lib\site-packages\sqlalchemy\engine\url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "c:\users\t41765\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 221, in load
    (self.group, name))
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqlit

**Comment by Siddapa** [comment]
NVM solved it!

**Comment by knowledgemule** [comment]
Just curious how did you solve it? I have been having issues of __init__ importing the Config file for som reason.

**Comment by Siddapa** [comment]
It had nothing really to do with my problem. Just a typo :)
