### ISSUE TITLE
ModuleNotFoundError: No module named 'flask.ext'

### ISSUE THREAD

**Issue by mossonli** [miguelgrinberg/microblog#129]
python -V 3.6.3
when I run the program 
Traceback (most recent call last):
  File "/Users/mosson/Downloads/microblog-master/microblog.py", line 1, in <module>
    from app import create_app, db, cli
  File "/Users/mosson/Downloads/microblog-master/app/__init__.py", line 5, in <module>
    from flask_sqlalchemy import SQLAlchemy
  File "/Users/mosson/envs/flask_env_3.6/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 30, in <module>
    from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
ModuleNotFoundError: No module named 'flask.ext'

**Comment by ashburry-chat-irc** [comment]
Error with latest install of flask_sqalchemy as far as i know.
```
from flask_sqlalchemy import SQLAlchemy
  File "C:\Users\ashbu\Documents\trio-ircproxy\trio-ircproxy\venv\Lib\site-packages\flask_sqlalchemy\__init__.py", line 30, in <module>
    from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
ModuleNotFoundError: No module named 'flask.ext'
```

**Comment by miguelgrinberg** [comment]
@ashburry-chat-irc Try upgrading your dependencies. You have some very old ones in there.
