### ISSUE TITLE
Thread error

### ISSUE THREAD

**Issue by JanZaplatil** [miguelgrinberg/microblog#133]
i have a problem with commitig data to db. 

models.py 

class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(64), index=True, unique=True)
    description = db.Column(db.String(120), index=True, unique=True)
    start = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return '<Task {}>'.format(self.task)

config.py 

class Config(object):
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'you-will-never-guess'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \
                              'sqlite:///' + os.path.join(basedir, 'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False

__inti__.py 

from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app import routes, models

i have a problem committing data or starting any new queries in python interpreter. Because each time i do a get an thread error:

Traceback (most recent call last):
  File "/Users/janzaplatil/Desktop/taskmanager/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/janzaplatil/Desktop/taskmanager/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 639, in _init_compiled
    self.cursor = self.create_cursor()
  File "/Users/janzaplatil/Desktop/taskmanager/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 954, in create_cursor
    return self._dbapi_connection.cursor()
  File "/Users/janzaplatil/Desktop/taskmanager/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 977, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145556750336 and this is thread id 140735588914048.
The above exception was the direct cause of the following exception:

sometimes it works if i run a db.session.rollback() command but if i try to run tasks = Task.query.all() than it does not. 

sory for bothering you i have no idea what to do

**Comment by miguelgrinberg** [comment]
I need to see a complete session in the Python shell, until you get the error.

**Comment by JanZaplatil** [comment]
PyDev console: starting.
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28) 
[Clang 6.0 (clang-600.0.57)] on darwin
from app.models import Task
u = Task(task='zlozi', description='zlozi hlace')
u
<Task zlozi>
db.session.add(u)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'db' is not defined
from app.models import db
db.session.add(u)
db.session.commit()
tasks = Task.query.all()

than the error listed above appears

**Comment by miguelgrinberg** [comment]
Can you try running the same test but this time using my code? This error is odd in this situation, because you are not using multiple threads. Makes me think something in your version of the code is different.

**Comment by JanZaplatil** [comment]
ok so i did it like this i started a new project in new venv so it should be isolated if i understand it right. 
2. i downloaded your https://github.com/miguelgrinberg/microblog/tree/v0.4 part 4 database zip 
3. i did all the imports in terminal...flask , wtf, 
4. now the commit part:
(venv) Jans-MBP:microblog2 janzaplatil$ flask db init
Error: Directory migrations already exists  **dont understand why if i started from scratch **
(venv) Jans-MBP:microblog2 janzaplatil$ flask db migrate -m "users table"
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [root] Error: Target database is not up to date. **again how if it is new**
(venv) Jans-MBP:microblog2 janzaplatil$ flask db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e517276bb1c2, users table
INFO  [alembic.runtime.migration] Running upgrade e517276bb1c2 -> 780739b227a7, posts table
(venv) Jans-MBP:microblog2 janzaplatil$ flask db migrate -m "posts table"
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.env] No changes in schema detected.
(venv) Jans-MBP:microblog2 janzaplatil$ flask db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
(venv) Jans-MBP:microblog2 janzaplatil$ 

**now in python console**

from app.models import User
u = User(username='susan', email='susan@example.com')
u
<User susan>
from app import db
from app.models import User, Post
u = User(username='john', email='john@example.com')
db.session.add(u)
db.session.commit()
u = User(username='susan', email='susan@example.com')
db.session.add(u)
db.session.commit()
Traceback (most recent call last):
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 639, in _init_compiled
    self.cursor = self.create_cursor()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 954, in create_cursor
    return self._dbapi_connection.cursor()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 977, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145525743616 and this is thread id 140735588914048.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2345, in _flush
    flush_context.execute()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1132, in _execute_context
    None, None)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 639, in _init_compiled
    self.cursor = self.create_cursor()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 954, in create_cursor
    return self._dbapi_connection.cursor()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 977, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145525743616 and this is thread id 140735588914048. [SQL: 'INSERT INTO user (username, email, password_hash) VALUES (?, ?, ?)'] [parameters: [{'username': 'susan', 'email': 'susan@example.com', 'password_hash': None}]] (Background on this error at: http://sqlalche.me/e/f405)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 704, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 459, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145525743616 and this is thread id 140735588914048.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2381, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 76, in __exit__
    compat.reraise(type_, value, traceback)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2381, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 532, in rollback
    util.reraise(*rollback_err)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 497, in rollback
    t[1].rollback()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1632, in rollback
    self._do_rollback()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1670, in _do_rollback
    self.connection._rollback_impl()
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 706, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 704, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/janzaplatil/Desktop/microblog2/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 459, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145525743616 and this is thread id 140735588914048. (Background on this error at: http://sqlalche.me/e/f405)

**Comment by miguelgrinberg** [comment]
Regarding your questions:

> (venv) Jans-MBP:microblog2 janzaplatil$ flask db init
> Error: Directory migrations already exists **dont understand why if i started from scratch **

You really didn't start from scratch. My code includes a migration repository. The `flask db init` command is used to create the repository, it is not used when you get someone else's code that comes with migrations included.

> (venv) Jans-MBP:microblog2 janzaplatil$ flask db migrate -m "users table"
> INFO [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO [alembic.runtime.migration] Will assume non-transactional DDL.
> ERROR [root] Error: Target database is not up to date. again how if it is new

Same as above. This repository includes the database migrations, you are trying to generate them yourself and that fails.

> now in python console

Is this really a Python console, or are you using a different shell? In your previous post you appeared to be using PyDev. Do you get the error if you use the normal Python shell instead?

**Comment by JanZaplatil** [comment]
i am using a pycharm and to write these commands now in python console

from app.models import User
u = User(username='susan', email='susan@example.com')
u

from app import db
from app.models import User, Post
u = User(username='john', email='john@example.com')
db.session.add(u)
db.session.commit()
u = User(username='susan', email='susan@example.com')
db.session.add(u)
db.session.commit()

i open python console

should i be doing this directly in terminal ?

**Comment by miguelgrinberg** [comment]
It could be that the way the PyCharm terminal works conflicts with the way SQLite works, so maybe that is the problem and you have to use the normal Python shell.

The `UNIQUE constraint failed: user.username` error means that you are adding a duplicate user to your database, which is not allowed.

**Comment by jacovanniekerk** [comment]
Yes, I got this as well in PyCharm.  Opening a terminal, activating the environment manually and issuing the commands, works perfectly.
