### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rohitkatlaa** [miguelgrinberg/microblog#147]
I am getting this error when i flask run it. I also switched the debugger off and still it is not working.

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rohit/Desktop/practice/flask/Hermes2.0/app/email.py", line 26, in send_async_email
    mail.send(msg)
  File "/home/rohit/Desktop/practice/flask/Hermes2.0/vir_env/lib/python3.6/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/rohit/Desktop/practice/flask/Hermes2.0/vir_env/lib/python3.6/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/rohit/Desktop/practice/flask/Hermes2.0/vir_env/lib/python3.6/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/usr/lib/python3.6/smtplib.py", line 697, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

**Comment by miguelgrinberg** [comment]
The email server that you configured in your application does not support authenticated clients. You may need to remove the authentication settings, or use a different email server.

**Comment by rohitkatlaa** [comment]
Can you please tell me how to do it

**Comment by miguelgrinberg** [comment]
I can't tell you how to do it. You created your configuration, right? You need to fix the details that configure your email server, that's all there is to it. Adding or removing environment variables until the configuration is right.

**Comment by rohitkatlaa** [comment]
Thank you

**Comment by rohitkatlaa** [comment]
I will do it

**Comment by rohitkatlaa** [comment]
I got an error when I tried to deploy my app in the heroku platform and I
typed heroku logs--tail please help me

2019-01-26T07:10:05.969392+00:00 app[web.1]: [2019-01-26 07:10:05 +0000]
[4] [INFO] Starting gunicorn 19.7.1
2019-01-26T07:10:05.970015+00:00 app[web.1]: [2019-01-26 07:10:05 +0000]
[4] [INFO] Listening at: http://0.0.0.0:23487 (4)
2019-01-26T07:10:05.970189+00:00 app[web.1]: [2019-01-26 07:10:05 +0000]
[4] [INFO] Using worker: sync
2019-01-26T07:10:05.974067+00:00 app[web.1]: [2019-01-26 07:10:05 +0000]
[10] [INFO] Booting worker with pid: 10
2019-01-26T07:10:06.033968+00:00 app[web.1]: [2019-01-26 07:10:06 +0000]
[11] [INFO] Booting worker with pid: 11
2019-01-26T07:10:06.835450+00:00 heroku[web.1]: State changed from starting
to crashed
2019-01-26T07:10:06.817567+00:00 heroku[web.1]: Process exited with status 3
2019-01-26T07:10:09.000000+00:00 app[api]: Build succeeded
2019-01-26T07:10:12.438634+00:00 heroku[web.1]: Starting process with
command `gunicorn app:app`
2019-01-26T07:10:14.414508+00:00 app[web.1]: [2019-01-26 07:10:14 +0000]
[4] [INFO] Starting gunicorn 19.7.1
2019-01-26T07:10:14.415340+00:00 app[web.1]: [2019-01-26 07:10:14 +0000]
[4] [INFO] Listening at: http://0.0.0.0:57823 (4)
2019-01-26T07:10:14.415511+00:00 app[web.1]: [2019-01-26 07:10:14 +0000]
[4] [INFO] Using worker: sync
2019-01-26T07:10:14.419529+00:00 app[web.1]: [2019-01-26 07:10:14 +0000]
[10] [INFO] Booting worker with pid: 10
2019-01-26T07:10:14.429983+00:00 app[web.1]: [2019-01-26 07:10:14 +0000]
[11] [INFO] Booting worker with pid: 11
2019-01-26T07:11:52.278352+00:00 heroku[web.1]: State changed from starting
to up
2019-01-26T07:11:52.952902+00:00 app[web.1]: [2019-01-26 07:11:52 +0000]
[15] [ERROR] Exception in worker process
2019-01-26T07:11:52.952916+00:00 app[web.1]: Traceback (most recent call
last):
2019-01-26T07:11:52.952918+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
578, in spawn_worker
2019-01-26T07:11:52.952920+00:00 app[web.1]: worker.init_process()
2019-01-26T07:11:52.952923+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py",
line 126, in init_process
2019-01-26T07:11:52.952925+00:00 app[web.1]: self.load_wsgi()
2019-01-26T07:11:52.952927+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py",
line 135, in load_wsgi
2019-01-26T07:11:52.952928+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-01-26T07:11:52.952931+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py",
line 67, in wsgi
2019-01-26T07:11:52.952932+00:00 app[web.1]: self.callable = self.load()
2019-01-26T07:11:52.952934+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py",
line 65, in load
2019-01-26T07:11:52.952936+00:00 app[web.1]: return self.load_wsgiapp()
2019-01-26T07:11:52.952938+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py",
line 52, in load_wsgiapp
2019-01-26T07:11:52.952940+00:00 app[web.1]: return
util.import_app(self.app_uri)
2019-01-26T07:11:52.952942+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line
352, in import_app
2019-01-26T07:11:52.952943+00:00 app[web.1]: __import__(module)
2019-01-26T07:11:52.952945+00:00 app[web.1]: File "/app/Hermes.py", line 1,
in <module>
2019-01-26T07:11:52.952947+00:00 app[web.1]: from app import app, database
2019-01-26T07:11:52.952949+00:00 app[web.1]: File "/app/app/__init__.py",
line 26, in <module>
2019-01-26T07:11:52.952951+00:00 app[web.1]: from app import routes,
models,errors
2019-01-26T07:11:52.952952+00:00 app[web.1]: File "/app/app/routes.py",
line 4, in <module>
2019-01-26T07:11:52.952954+00:00 app[web.1]: from PIL import Image
2019-01-26T07:11:52.959846+00:00 app[web.1]: ModuleNotFoundError: No module
named 'PIL'
2019-01-26T07:11:52.960716+00:00 app[web.1]: [2019-01-26 07:11:52 +0000]
[15] [INFO] Worker exiting (pid: 15)
2019-01-26T07:11:53.179494+00:00 app[web.1]: [2019-01-26 07:11:53 +0000]
[16] [ERROR] Exception in worker process
2019-01-26T07:11:53.179498+00:00 app[web.1]: Traceback (most recent call
last):
2019-01-26T07:11:53.179500+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
578, in spawn_worker
2019-01-26T07:11:53.179503+00:00 app[web.1]: worker.init_process()
2019-01-26T07:11:53.179504+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py",
line 126, in init_process
2019-01-26T07:11:53.179506+00:00 app[web.1]: self.load_wsgi()
2019-01-26T07:11:53.179508+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py",
line 135, in load_wsgi
2019-01-26T07:11:53.179510+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-01-26T07:11:53.179512+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py",
line 67, in wsgi
2019-01-26T07:11:53.179513+00:00 app[web.1]: self.callable = self.load()
2019-01-26T07:11:53.179515+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py",
line 65, in load
2019-01-26T07:11:53.179517+00:00 app[web.1]: return self.load_wsgiapp()
2019-01-26T07:11:53.179519+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py",
line 52, in load_wsgiapp
2019-01-26T07:11:53.179520+00:00 app[web.1]: return
util.import_app(self.app_uri)
2019-01-26T07:11:53.179531+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line
352, in import_app
2019-01-26T07:11:53.179533+00:00 app[web.1]: __import__(module)
2019-01-26T07:11:53.179535+00:00 app[web.1]: File "/app/Hermes.py", line 1,
in <module>
2019-01-26T07:11:53.179536+00:00 app[web.1]: from app import app, database
2019-01-26T07:11:53.179539+00:00 app[web.1]: File "/app/app/__init__.py",
line 26, in <module>
2019-01-26T07:11:53.179540+00:00 app[web.1]: from app import routes,
models,errors
2019-01-26T07:11:53.179542+00:00 app[web.1]: File "/app/app/routes.py",
line 4, in <module>
2019-01-26T07:11:53.179544+00:00 app[web.1]: from PIL import Image
2019-01-26T07:11:53.179545+00:00 app[web.1]: ModuleNotFoundError: No module
named 'PIL'
2019-01-26T07:11:53.180255+00:00 app[web.1]: [2019-01-26 07:11:53 +0000]
[16] [INFO] Worker exiting (pid: 16)
2019-01-26T07:11:53.401592+00:00 app[web.1]: Traceback (most recent call
last):
2019-01-26T07:11:53.401666+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
209, in run
2019-01-26T07:11:53.402087+00:00 app[web.1]: self.sleep()
2019-01-26T07:11:53.402130+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
359, in sleep
2019-01-26T07:11:53.402455+00:00 app[web.1]: ready =
select.select([self.PIPE[0]], [], [], 1.0)
2019-01-26T07:11:53.402697+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
244, in handle_chld
2019-01-26T07:11:53.402960+00:00 app[web.1]: self.reap_workers()
2019-01-26T07:11:53.402996+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
524, in reap_workers
2019-01-26T07:11:53.403378+00:00 app[web.1]: raise HaltServer(reason,
self.WORKER_BOOT_ERROR)
2019-01-26T07:11:53.403455+00:00 app[web.1]: gunicorn.errors.HaltServer:
<HaltServer 'Worker failed to boot.' 3>
2019-01-26T07:11:53.403485+00:00 app[web.1]:
2019-01-26T07:11:53.403488+00:00 app[web.1]: During handling of the above
exception, another exception occurred:
2019-01-26T07:11:53.403490+00:00 app[web.1]:
2019-01-26T07:11:53.403521+00:00 app[web.1]: Traceback (most recent call
last):
2019-01-26T07:11:53.403554+00:00 app[web.1]: File
"/app/.heroku/python/bin/gunicorn", line 11, in <module>
2019-01-26T07:11:53.403720+00:00 app[web.1]: sys.exit(run())
2019-01-26T07:11:53.403755+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py",
line 74, in run
2019-01-26T07:11:53.403953+00:00 app[web.1]: WSGIApplication("%(prog)s
[OPTIONS] [APP_MODULE]").run()
2019-01-26T07:11:53.403991+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py",
line 203, in run
2019-01-26T07:11:53.404237+00:00 app[web.1]: super(Application, self).run()
2019-01-26T07:11:53.404274+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py",
line 72, in run
2019-01-26T07:11:53.404456+00:00 app[web.1]: Arbiter(self).run()
2019-01-26T07:11:53.404490+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
231, in run
2019-01-26T07:11:53.404736+00:00 app[web.1]: self.halt(reason=inst.reason,
exit_status=inst.exit_status)
2019-01-26T07:11:53.405672+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
344, in halt
2019-01-26T07:11:53.406001+00:00 app[web.1]: self.stop()
2019-01-26T07:11:53.406037+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
393, in stop
2019-01-26T07:11:53.406384+00:00 app[web.1]: time.sleep(0.1)
2019-01-26T07:11:53.406420+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
244, in handle_chld
2019-01-26T07:11:53.406726+00:00 app[web.1]: self.reap_workers()
2019-01-26T07:11:53.406759+00:00 app[web.1]: File
"/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line
524, in reap_workers
2019-01-26T07:11:53.407130+00:00 app[web.1]: raise HaltServer(reason,
self.WORKER_BOOT_ERROR)
2019-01-26T07:11:53.407179+00:00 app[web.1]: gunicorn.errors.HaltServer:
<HaltServer 'Worker failed to boot.' 3>
2019-01-26T07:11:53.528952+00:00 heroku[web.1]: State changed from up to
crashed
2019-01-26T07:11:53.513434+00:00 heroku[web.1]: Process exited with status 1
2019-01-26T07:13:25.770871+00:00 heroku[router]: at=error code=H10
desc="App crashed" method=GET path="/" host=hermesmessenger.herokuapp.com
request_id=54426e9f-843d-4a39-a5f0-8ea94848f83c fwd="113.30.156.68" dyno=
connect= service= status=503 bytes= protocol=https
2019-01-26T07:13:26.077474+00:00 heroku[router]: at=error code=H10
desc="App crashed" method=GET path="/favicon.ico" host=
hermesmessenger.herokuapp.com
request_id=84c0b703-1e19-4c17-a32a-2854fba887a9 fwd="113.30.156.68" dyno=
connect= service= status=503 bytes= protocol=https

**Comment by rohitkatlaa** [comment]
Thank you so much for helping me.Now my app is deployed and running.
