### ISSUE TITLE
Issue with flask db init and config file syntax .Invalid syntax with basedir instance ?

### ISSUE THREAD

**Issue by BalaKrishna486** [miguelgrinberg/microblog#152]
File "/Users/ushakiran/Desktop/microblog/config.py", line 2
    basedir = os.path.abspath(os.path.dirname(__file__))
                                                        ^
SyntaxError: invalid syntax

how can i overcome this issue , have checked the code multiple times with no lock 
this occurs when i ran - flask db init from main directory

**Comment by miguelgrinberg** [comment]
Please make an exact copy of your terminal or a screenshot, including the command that you typed and the complete output, not just the error.

**Comment by christianoruge** [comment]
I get the same problem.
Any suggestions?

Here is the Terminal report:

Kind regards, Christian Otto Ruge

(venv) BM-C0D9E-006:CORals_nett bm940$ flask db init
Traceback (most recent call last):
  File "/Users/bm940/Documents/CORals_nett/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/Users/bm940/Documents/CORals_nett/venv/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/bm940/Documents/CORals_nett/CORals_nett.py", line 1, in <module>
    from app import app 
  File "/Users/bm940/Documents/CORals_nett/app/__init__.py", line 2, in <module>
    from config import Config
  File "/Users/bm940/Documents/CORals_nett/config.py", line 5
    SQLALCHEMY_DATABASE_URI=os.environ.get('DATABASE_URL')) or \'sqlite:/// + os.path.join(basedir, 'app.db')
                                                          ^
SyntaxError: invalid syntax
(venv) BM-C0D9E-006:CORals_nett bm940$

**Comment by miguelgrinberg** [comment]
@christianoruge you have a syntax error in your application:

```
File "/Users/bm940/Documents/CORals_nett/config.py", line 5
SQLALCHEMY_DATABASE_URI=os.environ.get('DATABASE_URL')) or 'sqlite:/// + os.path.join(basedir, 'app.db')
^
SyntaxError: invalid syntax
```

Can't say for sure, but it seems you didn't close a quote in ``sqlite:///'`.
