### ISSUE TITLE
Section 6: More Interesting profiles, Operational error occurs after applying Upgrade.

### ISSUE THREAD

**Issue by Nooria999** [miguelgrinberg/microblog#165]
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 36694d345787 -> 58b088d8fad0, new fields in user model
Traceback (most recent call last):
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: duplicate column name: timestamp

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\__main__.py", line 14, in <module>
    main(as_module=True)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\cli.py", line 906, in main
    cli.main(args=args, prog_name=name)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\cli.py", line 419, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_migrate\cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_migrate\__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_migrate\__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\command.py", line 276, in upgrade
    script.run_env()
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\script\base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\util\pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\util\compat.py", line 156, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations\env.py", line 96, in <module>
    run_migrations_online()
  File "migrations\env.py", line 90, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\runtime\environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\runtime\migration.py", line 361, in run_migrations
    step.migration_fn(**kw)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\migrations\versions\58b088d8fad0_new_fields_in_user_model.py", line 21, in upgrade
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\operations\ops.py", line 1904, in add_column
    return operations.invoke(op)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\operations\base.py", line 345, in invoke
    return fn(self, operation)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\operations\toimpl.py", line 131, in add_column
    operations.impl.add_column(table_name, column, schema=schema)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\ddl\impl.py", line 230, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\alembic\ddl\impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1050, in _execute_ddl
    compiled,
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\nooria.ali\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: timestamp
[SQL: ALTER TABLE post ADD COLUMN timestamp DATETIME]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by miguelgrinberg** [comment]
This is because your database is out of sync with the migration scripts. The error indicates that your database has a `timestamp` column in table `post`, but the migration that your are trying to run is adding the same column again.

**Comment by Nooria999** [comment]
Yes, I understand that but, I was passing the migrate for adding "new fields in user model" which were last_seen and about_me. Since then it is returning this error, I'm sorry but I'm a little clueless as to how I can rectify it. Could you help me out?
Also, how can I view my database?

**Comment by miguelgrinberg** [comment]
@Nooria999 do you have anything important in your database? If not, the easiest way out of this problem is to regenerate the database from scratch:

- First delete the migration file that has the problem, which according to your logs starts with `58b088d8fad0`.
- Then delete your database file.
- Finally, run `flask db upgrade`.

Now you have a fresh database that does not include the new fields in the user model. You can generate a migration for those fields with `flask db migrate`. Then do `flask db upgrade` to add those fields to the database.

If any of this gives you the same or other errors, please show me what you get, and that will probably give me a better idea of the problem might be. I think it is unlikely, but maybe one of your previous migrations is also bad.

**Comment by Nooria999** [comment]
Thankyou so much!
I deleted my database and all various versions of the migrations I had passed and started all over, and it is working normally now.
