### ISSUE TITLE
error db.session.commit()

### ISSUE THREAD

**Issue by chilakill** [miguelgrinberg/microblog#170]
estoy trabajando sobre el código publicado en el blog pero cuando intento hacer el ejercicio de agregar usuarios me arroja un error, ya he buscado pero no encuentro respuesta.

`from app import db
from app.models import User, Post
u= User(username='Carlos',email='lkj@jaksl.com')
db.session.add(u)
db.session.commit()
u = User(username='susan', email='susan@example.com')
db.session.add(u)
db.session.commit()
Traceback (most recent call last):
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 686, in _init_compiled
    self.cursor = self.create_cursor()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1038, in create_cursor
    return self._dbapi_connection.cursor()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 965, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145368551424 and this is thread id 4673062336.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1138, in _emit_insert_statements
    statement, params
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 686, in _init_compiled
    self.cursor = self.create_cursor()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1038, in create_cursor
    return self._dbapi_connection.cursor()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 965, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145368551424 and this is thread id 4673062336.
[SQL: INSERT INTO user (username, email, password_hash) VALUES (?, ?, ?)]
[parameters: [{'username': 'susan', 'email': 'susan@example.com', 'password_hash': None}]]
(Background on this error at: http://sqlalche.me/e/f405)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 739, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 500, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145368551424 and this is thread id 4673062336.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 79, in __exit__
    compat.reraise(type_, value, traceback)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 154, in reraise
    raise value
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 564, in rollback
    util.reraise(*rollback_err)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 154, in reraise
    raise value
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 524, in rollback
    t[1].rollback()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1705, in rollback
    self._do_rollback()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1743, in _do_rollback
    self.connection._rollback_impl()
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 741, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 739, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/julioctello/anaconda3/envs/microblog/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 500, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145368551424 and this is thread id 4673062336.
(Background on this error at: http://sqlalche.me/e/f405)
`

**Comment by chilakill** [comment]
después del error hice un db.session.rollback()
intente hacerlo desde el interprete de visual studio code, y ya no aparecen mayores problemas,

el problema es usar PYCHARM
