### ISSUE TITLE
How to rename column on MySQL without deleting existing data?

### ISSUE THREAD

**Issue by mrbiggleswirth** [miguelgrinberg/microblog#179]
### Setup:
mysql> **SELECT version();**

* 5.7.27-0ubuntu0.18.04.1
* Python 3.6.8
* SQLAlchemy 1.3.6
* Alembic 1.0.11

.

**models.py:**
```
class Experiments(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    # country = db.Column(db.String(100))
    countryland = db.Column(db.String(100))

    insert_date = db.Column(db.DateTime, index=True,
        default=datetime.utcnow)
```

.

**SQL data:**
```
INSERT INTO experiments (country)
VALUES ('US'),
       ('Canada'),
       ('Mexico'),
       ('Brazil'),
       ('Argentina'),
       ('Spain'),
       ('Portugal'),
       ('France'),
       ('Germany'),
       ('UK');
```

.

**migration file:**
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # op.add_column('experiments',
                   # sa.Column('countryland',
                   # sa.String(length=100),
                   # nullable=True))

    # op.drop_column('experiments', 'country')

    op.alter_column('experiments',
                     column_name='country',
                     new_column_name='countryland',
                     existing_type='String',
                     existing_nullable=False,
                     existing_server_default='Greenland')

    # ### end Alembic commands ###
```

.

### Problem:
I want to rename the column name from **"country"** to **"countryland"**. But I'm getting this error in my terminal can anybody help me please?

I was told that you need to specify certain parameters for MySQL's **alter_column()** operation to execute properly. But I'm not sure what values to fill in just from this Alembic documentation.
https://alembic.sqlalchemy.org/en/latest/ops.html?highlight=alter_column#alembic.operations.Operations.alter_column

.

### Error
```
$ flask db upgrade

[2019-08-29 12:37:19,080] INFO in __init__: microblog startup
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 1f866a4fa5a0 -> 69e7cfcf87f1, Testing column rename 02.

Traceback (most recent call last):
  File "/home/linux/.local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/linux/.local/lib/python3.6/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/home/linux/.local/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/linux/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linux/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linux/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linux/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/home/linux/.local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/util/compat.py", line 177, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 96, in <module>
    run_migrations_online()
  File "migrations/env.py", line 90, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 362, in run_migrations
    step.migration_fn(**kw)

  File "/mnt/c/Users/tux/Desktop/Web/microblog/migrations/versions/69e7cfcf87f1_testing_column_rename_02.py", line 34, in upgrade
    existing_server_default='Greenland')
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/operations/ops.py", line 1775, in alter_column
    return operations.invoke(alt)
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 56, in alter_column
    **operation.kw
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/ddl/mysql.py", line 67, in alter_column
    else existing_autoincrement,
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1043, in _execute_ddl
    else None,
  File "<string>", line 1, in <lambda>
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 462, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 436, in <lambda>
    lambda *arg, **kw: existing(*arg, **kw),
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 478, in __call__
    return fn(element, compiler, **kw)
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/ddl/mysql.py", line 390, in _mysql_change_column
    comment=element.comment,
  File "/home/linux/.local/lib/python3.6/site-packages/alembic/ddl/mysql.py", line 406, in _mysql_colspec
    compiler.dialect.type_compiler.process(type_),
  File "/home/linux/.local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 400, in process
    return type_._compiler_dispatch(self, **kw)

AttributeError: 'str' object has no attribute '_compiler_dispatch'

```

**Comment by miguelgrinberg** [comment]
This is probably the column type, which you've given as `'String'` instead of the proper column class, such as `String(100)`.

**Comment by mrbiggleswirth** [comment]
It worked thanks!

**models.py:**
```
class Experiments(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    kountry = db.Column(db.String(100))
    #countryland = db.Column(db.String(100))

    insert_date = db.Column(db.DateTime, index=True,
        default=datetime.utcnow)
```

.

**migration file:**
```
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # op.add_column('experiments', sa.Column('kountry', sa.String(length=100), nullable=True))
    # op.drop_column('experiments', 'countryland')

    op.alter_column('experiments',
                     column_name = 'countryland',
                     new_column_name = 'kountry',
                     existing_type = sa.String(100),
                     existing_nullable = False,
                     existing_server_default = 'Greenland')

    # ### end Alembic commands ###

```
