### ISSUE TITLE
Error with postgres

### ISSUE THREAD

**Issue by MarkoShiva** [miguelgrinberg/microblog#192]
I get the error with missing tables. I thought that migrate should do that automatically. 
how to mitigate error,

```
2019-11-26T14:47:36.910809+00:00 app[web.1]: [2019-11-26 14:47:36,899] ERROR in app: Exception on /auth/register [POST]
2019-11-26T14:47:36.910823+00:00 app[web.1]: Traceback (most recent call last):
2019-11-26T14:47:36.910827+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
2019-11-26T14:47:36.910829+00:00 app[web.1]: cursor, statement, parameters, context
2019-11-26T14:47:36.910831+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
2019-11-26T14:47:36.910833+00:00 app[web.1]: cursor.execute(statement, parameters)
2019-11-26T14:47:36.910836+00:00 app[web.1]: psycopg2.errors.UndefinedTable: relation "user" does not exist
2019-11-26T14:47:36.910838+00:00 app[web.1]: LINE 2: FROM "user"
2019-11-26T14:47:36.910841+00:00 app[web.1]: ^
2019-11-26T14:47:36.910842+00:00 app[web.1]: 
2019-11-26T14:47:36.910844+00:00 app[web.1]: 
2019-11-26T14:47:36.910845+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2019-11-26T14:47:36.910847+00:00 app[web.1]: 
2019-11-26T14:47:36.910848+00:00 app[web.1]: Traceback (most recent call last):
2019-11-26T14:47:36.910865+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
2019-11-26T14:47:36.910867+00:00 app[web.1]: response = self.full_dispatch_request()
2019-11-26T14:47:36.910869+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
2019-11-26T14:47:36.910871+00:00 app[web.1]: rv = self.handle_user_exception(e)
2019-11-26T14:47:36.910873+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
2019-11-26T14:47:36.910875+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2019-11-26T14:47:36.910877+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
2019-11-26T14:47:36.910879+00:00 app[web.1]: raise value
2019-11-26T14:47:36.910881+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
2019-11-26T14:47:36.910883+00:00 app[web.1]: rv = self.dispatch_request()
2019-11-26T14:47:36.910885+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
2019-11-26T14:47:36.910887+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2019-11-26T14:47:36.910888+00:00 app[web.1]: File "/app/app/auth/routes.py", line 42, in register
2019-11-26T14:47:36.910890+00:00 app[web.1]: if form.validate_on_submit():
2019-11-26T14:47:36.910891+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
2019-11-26T14:47:36.910893+00:00 app[web.1]: return self.is_submitted() and self.validate()
2019-11-26T14:47:36.910895+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/wtforms/form.py", line 310, in validate
2019-11-26T14:47:36.910896+00:00 app[web.1]: return super(Form, self).validate(extra)
2019-11-26T14:47:36.910898+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/wtforms/form.py", line 152, in validate
2019-11-26T14:47:36.910899+00:00 app[web.1]: if not field.validate(self, extra):
2019-11-26T14:47:36.910901+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/wtforms/fields/core.py", line 206, in validate
2019-11-26T14:47:36.910902+00:00 app[web.1]: stop_validation = self._run_validation_chain(form, chain)
2019-11-26T14:47:36.910904+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
2019-11-26T14:47:36.910905+00:00 app[web.1]: validator(form, self)
2019-11-26T14:47:36.910907+00:00 app[web.1]: File "/app/app/auth/forms.py", line 25, in validate_username
2019-11-26T14:47:36.910908+00:00 app[web.1]: user = User.query.filter_by(username=username.data).first()
2019-11-26T14:47:36.910910+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3265, in first
2019-11-26T14:47:36.910911+00:00 app[web.1]: ret = list(self[0:1])
2019-11-26T14:47:36.910913+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
2019-11-26T14:47:36.910914+00:00 app[web.1]: return list(res)
2019-11-26T14:47:36.910916+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
2019-11-26T14:47:36.910917+00:00 app[web.1]: return self._execute_and_instances(context)
2019-11-26T14:47:36.910919+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
2019-11-26T14:47:36.910920+00:00 app[web.1]: resul
```

**Comment by in1t3r** [comment]
continued
```
2019-11-26T14:47:36.910920+00:00 app[web.1]: result = conn.execute(querycontext.statement, self._params)
2019-11-26T14:47:36.910922+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
2019-11-26T14:47:36.910923+00:00 app[web.1]: return meth(self, multiparams, params)
2019-11-26T14:47:36.910925+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
2019-11-26T14:47:36.910926+00:00 app[web.1]: return connection._execute_clauseelement(self, multiparams, params)
2019-11-26T14:47:36.910928+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
2019-11-26T14:47:36.910929+00:00 app[web.1]: distilled_params,
2019-11-26T14:47:36.910931+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
2019-11-26T14:47:36.910932+00:00 app[web.1]: e, statement, parameters, cursor, context
2019-11-26T14:47:36.910934+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
2019-11-26T14:47:36.910935+00:00 app[web.1]: util.raise_from_cause(sqlalchemy_exception, exc_info)
2019-11-26T14:47:36.910936+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
2019-11-26T14:47:36.910938+00:00 app[web.1]: reraise(type(exception), exception, tb=exc_tb, cause=cause)
2019-11-26T14:47:36.910945+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
2019-11-26T14:47:36.910946+00:00 app[web.1]: raise value.with_traceback(tb)
2019-11-26T14:47:36.910948+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
2019-11-26T14:47:36.910949+00:00 app[web.1]: cursor, statement, parameters, context
2019-11-26T14:47:36.910951+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
2019-11-26T14:47:36.910952+00:00 app[web.1]: cursor.execute(statement, parameters)
2019-11-26T14:47:36.910954+00:00 app[web.1]: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "user" does not exist
2019-11-26T14:47:36.910955+00:00 app[web.1]: LINE 2: FROM "user"
2019-11-26T14:47:36.910957+00:00 app[web.1]: ^
2019-11-26T14:47:36.910958+00:00 app[web.1]: 
2019-11-26T14:47:36.910960+00:00 app[web.1]: [SQL: SELECT "user".id AS user_id, "user".username AS user_username, "user".email AS user_email, "user".password_hash AS user_password_hash, "user".about_me AS user_about_me, "user".last_seen AS user_last_seen
2019-11-26T14:47:36.910961+00:00 app[web.1]: FROM "user"
2019-11-26T14:47:36.910963+00:00 app[web.1]: WHERE "user".username = %(username_1)s
2019-11-26T14:47:36.910965+00:00 app[web.1]: LIMIT %(param_1)s]
2019-11-26T14:47:36.910966+00:00 app[web.1]: [parameters: {'username_1': 'shiva', 'param_1': 1}]
2019-11-26T14:47:36.910968+00:00 app[web.1]: (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by miguelgrinberg** [comment]
What is it that you expect migrate to do automatically? From looking at the error my guess is that you haven't applied a migration, or maybe you haven't even generated one that includes your users table.

**Comment by in1t3r** [comment]
hi @miguelgrinberg thanks for answering.
Well I have everything applied and working locally with sqlite. I haven't found anywhere in your tutorial reference to any of the steps that are needed for postgresql to work. I see you are adding it thru the terminal with `heroku addons:add heroku-postgresql:hobby-dev` I did that as well as other commands that you mentioned. 

I don't see anywhere command that is used to migrate for postgresql. 
My flask history:

```
flask db history
[2019-11-26 17:49:26,870] INFO in __init__: Microblog startup
af46ebeac802 -> bdac3d6f83a1 (head), add language to posts
4c18172b5c15 -> af46ebeac802, followers
87d3c2b6d5e7 -> 4c18172b5c15, new fields in user model
<base> -> 87d3c2b6d5e7, users table
```
Works locally with sqlite and I have users added via register...

**Comment by miguelgrinberg** [comment]
The process with Postgres is the same as with SQLite. If you have a migration history already in place and a new Postgres database created, then you need to configure your Postgres database URL and then run `flask db upgrade`.

**Comment by onlinejudge95** [comment]
@MarkoShiva have you created the database in `postgre`? In case of `sqlite` the database is automatically created.

**Comment by MarkoShiva** [comment]
I forgot to include migrations had them git ignored. It's solved.

**Comment by parismollo** [comment]
> I forgot to include migrations had them git ignored. It's solved.

Hello! @MarkoShiva I have the exact same issue but my migrations files are already in git... Do you have any idea how I can solve this?
