### ISSUE TITLE
TypeError: Object of type bytes is not JSON serializable in Chapter 5

### ISSUE THREAD

**Issue by Esshahn** [miguelgrinberg/microblog#204]
Thanks for the great tutorial.
Unfortunately, I keep having one issue every time I did this tut so far:

````
TypeError: Object of type bytes is not JSON serializable
````

Here's the full output:

````
esshahn@C65 pytut % source venv/bin/activate
(venv) esshahn@C65 pytut % flask run
 * Serving Flask app "microblog.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2020-01-29 15:43:50,772] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/esshahn/github/pytut/app/routes.py", line 30, in login
    form = LoginForm()
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/flask_wtf/csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/itsdangerous/serializer.py", line 166, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/itsdangerous/url_safe.py", line 42, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/itsdangerous/serializer.py", line 133, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
  File "/Users/esshahn/github/pytut/venv/lib/python3.7/site-packages/itsdangerous/_json.py", line 18, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
````

This happens as soon as the login page gets called.
I am at Chapter 5.
I have copy & pasted all source code from the repo to rule out any typos. It's still the same.
I'm pretty sure I installed everything from inside the venv.
I'm running out of ideas. Any hints?
Thank you very much.

**Comment by onlinejudge95** [comment]
You are trying to read JSON data but are passing bytes to it. Make sure that your content-type is set properly in your request.

**Comment by Esshahn** [comment]
Thanks for your reply. Let me clarify. I did understand what the error meant, but not where it happens. Since I'm doing the so far completely identical tutorial without any modifications, it is not something I'm doing wrong specifically.

**Comment by Esshahn** [comment]
I think I can track it down to 

````
form = LoginForm()
````

in routes.py

````
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.urls import url_parse
from app import app, db
from app.forms import LoginForm, RegistrationForm
from app.models import User


@app.route('/')
@app.route('/index')
@login_required
def index():
    posts = [
        {
            'author': {'username': 'John'},
            'body': 'Beautiful day in Portland!'
        },
        {
            'author': {'username': 'Susan'},
            'body': 'The Avengers movie was so cool!'
        }
    ]
    return render_template('index.html', title='Home', posts=posts)


@app.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('index')
        return redirect(next_page)
    return render_template('login.html', title='Sign In', form=form)


@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))


@app.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('login'))
    return render_template('register.html', title='Register', form=form)
````

As soon as I call that line, the error occurs.

**Comment by Esshahn** [comment]
I have found the issue (and it might help to have that solution in mind for others).
The problem is an old cookie as described here: https://stackoverflow.com/questions/44605393/object-of-type-bytes-is-not-json-serializable-when-upgrading-my-python-environ

````
As @Arpit Solanki mentioned, py2.x and py3.x are very different in case of encoding. You'd better clear your cookies in your browser, probably the browser had cookies set by python2 code, but your new python3 interpreted the cookie content as byte strings. Please clear your cookie will solve the issue.
````

Clearing the localhost cookie solved the issue.
