### ISSUE TITLE
Chapter 23.7.2: Token Requests (v0.23) - ImportError: cannot import name 'ImmutableDict'

### ISSUE THREAD

**Issue by mrbiggleswirth** [miguelgrinberg/microblog#215]
Hi I have followed along the instructions for **Chapter 23: API** up to the **23.7.2 Token Requests** section at page 327 (PDF 345) where I try to send a POST request to the tokens API route. This is the point where my entire Microblog project breaks down and I don't know where to fix the problem.

### Errors
```
$ http POST http://localhost:5000/api/tokens


http: error: ConnectionError: HTTPConnectionPool(host='localhost', port=5000):
Max retries exceeded with url: /api/tokens (Caused by NewConnectionError(
'<urllib3.connection.HTTPConnection object at 0x7f89881c5390>: Failed to
 establish a new connection: [Errno 111] Connection refused',))
while doing a POST request to URL: http://localhost:5000/api/tokens
```
.
```
$ export FLASK_APP=microblog.py
$ export FLASK_DEBUG=1
$ flask run


 * Serving Flask app "microblog.py" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 119-101-471

127.0.0.1 - - [13/Mar/2020 12:26:15] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/mnt/c/Users/Bill/Desktop/Python/microblog/microblog.py", line 1, in <module>
    from appz import cli
  File "/mnt/c/Users/Bill/Desktop/Python/microblog/appz/__init__.py", line 24, in <module>
    from flask_babel import Babel
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask_babel/__init__.py", line 19, in <module>
    from werkzeug import ImmutableDict
ImportError: cannot import name 'ImmutableDict'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/cli.py", line 338, in __call__
    self._flush_bg_loading_exception()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/cli.py", line 326, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/cli.py", line 314, in _load_app
    self._load_unlocked()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/cli.py", line 247, in locate_app
    "\n\n{tb}".format(name=module_name, tb=traceback.format_exc())
flask.cli.NoAppException: While importing "microblog", an ImportError was raised:


Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/mnt/c/Users/Bill/Desktop/Python/microblog/microblog.py", line 1, in <module>
    from appz import cli
  File "/mnt/c/Users/Bill/Desktop/Python/microblog/appz/__init__.py", line 24, in <module>
    from flask_babel import Babel
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask_babel/__init__.py", line 19, in <module>
    from werkzeug import ImmutableDict
ImportError: cannot import name 'ImmutableDict'
127.0.0.1 - - [13/Mar/2020 12:26:15] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [13/Mar/2020 12:26:15] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [13/Mar/2020 12:26:15] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [13/Mar/2020 12:26:15] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [13/Mar/2020 12:26:15] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```
.
### Microblog v.023 zipped source code
I tried the v.023 zipped source code from scratch and it looks like I'm getting the same errors as my Microblog learning code.
https://github.com/miguelgrinberg/microblog/releases/tag/v0.23
.
### Werkzeug
```
$ pip3 list
Werkzeug (1.0.0)
```
Looking at the Microblog tutorial's **requirements.txt** on github I see this `Werkzeug==0.14.1`. Does this mean I need to downgrade from my version `1.0.0` down to version `0.14.1`?
https://github.com/miguelgrinberg/microblog/blob/master/requirements.txt

**Comment by miguelgrinberg** [comment]
Upgrade Flask-Babel. You are using an old version, along with a more recent version of Werkzeug.

**Comment by mrbiggleswirth** [comment]
@miguelgrinberg 
Thanks Miguel everything is back on track again! 🚂💨

**March 14, 2020**
* Windows Subsystem for Linux (WSL)
```
# --- Default package versions ---

$ pip3 list

Flask-Babel (0.12.2)
Werkzeug (1.0.0)
Flask-WTF (0.14.2)

#_______________________________________________________________________________

$ pip3 install Flask-Babel --upgrade
$ pip3 install Werkzeug --upgrade
$ pip3 install Flask-WTF --upgrade

#_______________________________________________________________________________

# --- Upgraded package versions ---

$ pip3 list

Flask-Babel (1.0.0)
Werkzeug (1.0.0)
Flask-WTF (0.14.3)

#_______________________________________________________________________________

$ pwd
/mnt/c/Users/Bill/Desktop/Python/Flask Troubleshooting/microblog-0.23

$ flask db upgrade

```
.
```
# --- Terminal 1 ---

$ flask run

#_______________________________________________________________________________

# --- Terminal 2 ---

$ http POST http://localhost:5000/api/tokens

HTTP/1.0 401 UNAUTHORIZED
Content-Length: 30
Content-Type: application/json
Date: Sat, 14 Mar 2020 08:39:58 GMT
Server: Werkzeug/1.0.0 Python/3.6.8
WWW-Authenticate: Basic realm="Authentication Required"

{
    "error": "Unauthorized"
}

```
