### ISSUE TITLE
Deployed according to instructions in part-xvii, but now table is empty

### ISSUE THREAD

**Issue by FredButBetter** [miguelgrinberg/microblog#229]
Hey Miguel, thank you so much for all the incredible tutorials! I finally finished my project, which includes a fairly hefty database which requires being precompiled on my remote PC, and deployed to a Ubuntu 16.04 server and used mysql, just like your instructions mentioned. My site is now up and running, and I do not encounter any errors, everything works fine. Except, the only issue is that it seems to not be accessing my precompiled database. I used the flask db upgrade command like you instructed, and it did not throw an error. Am I misunderstanding something, or is there something more I must to do make my database discoverable by my site?

If you need any more information, I am happy to provide. Thank you again!

**Comment by miguelgrinberg** [comment]
Did you set your `DATABASE_URL` to point to your database?

**Comment by FredButBetter** [comment]
Yes, I have the following line in my .env file:

`DATABASE_URL=mysql+pymysql://<myuser>:<mypass>@localhost:3306/<appname>`

(obviously with the correct info in the <>'s) but if I have only that, then it throws me an error like this: 

`/home/<user>/<appname>/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:814: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
Traceback (most recent call last):
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: image`

To fix this error, I saw on another site that I would have to add the following line to my config file, which I did and it no longer threw me this error. 

`SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://<myuser>:<mypass>@localhost:3306/<appname>'`

I should also mention that I copied my database in the form of a .db file, and its name is the same as the <appname> in the URL and URI links above

**Comment by miguelgrinberg** [comment]
Based on the error message I think you need to verify that your `DATABASE_URL` environment variable is properly imported into the configuration. The `SQLALCHEMY_DATABASE_URI` setting is directly imported from the env variable, so something is definitely broken there.

**Comment by FredButBetter** [comment]
I took out the lines that I inserted having to do with the `SQLALCHEMY_DATABASE_URI` and tried to fiddle with the .env to see if it wasn't loading properly, but in every case, I end up with the following error (which is the same error I was seeing before I added the URI lines in the first place). I feel as though I am missing something with how the db should be loaded. Currently, I am just using a call as `db = SQLAlchemy(app)`, and I have left the .db file as app.db in the base folder of the app. Is there anything else I could be doing wrong that you think might be the issue here? 

`/home/<user>/<appname>/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:814: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
Traceback (most recent call last):
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<user>/<appname>/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/<user>/<appname>/<appname>.py", line 1, in <module>
    from app import app
  File "/home/<user>/<appname>/app/__init__.py", line 19, in <module>
    from app import models, routes
  File "/home/<user>/<appname>/app/routes.py", line 6, in <module>
    from FilterQueries import Artists, Genres, Startyears, Endyears, getReartists, getRegenres, getReyears, refilter
  File "/home/<user>/<appname>/FilterQueries.py", line 51, in <module>
    artistPreSplit = [row.artist for row in artistsQuery.all()]
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3233, in all
    return list(self)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/<user>/<appname>/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: image
[SQL: SELECT DISTINCT image.artist AS image_artist
FROM image]`

**Comment by miguelgrinberg** [comment]
The way you have implemented the configuration is wrong, the error message leaves no doubt about it. I cannot tell you what's wrong exactly, but you need to debug your configuration, that's where the problem is.
