### ISSUE TITLE
ch 22 background job 

### ISSUE THREAD

**Issue by playgoods** [miguelgrinberg/microblog#234]
dear Miguel , 

i tray send background job , but see this blew error 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./app/tasks.py", line 48, in export_posts
    sync=True)
  File "./app/email.py", line 21, in send_email
    mail.send(msg)
  File "/home/moh/microblog3/venv/lib/python3.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/moh/microblog3/venv/lib/python3.7/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python3.7/smtplib.py", line 984, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.7/smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.7/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/usr/lib/python3.7/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

when test reset password , can send by successfully

**Comment by miguelgrinberg** [comment]
Do you have the Flask-Mail environment variables in the context of your RQ worker?

**Comment by playgoods** [comment]
many many many thanks :)
