### ISSUE TITLE
import SocketServer as socketserver ModuleNotFoundError: No module named 'SocketServer'

### ISSUE THREAD

**Issue by Amazeryogo** [miguelgrinberg/microblog#238]
Hi, Miguel
It gives an error when I try to install SocketServer. How do I install and run SocketServer?

**Comment by Amazeryogo** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 56, in <module>
    from http.server import BaseHTTPRequestHandler
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/server.py", line 92, in <module>
    import email.utils
  File "/Users/suvid/Dropbox/My Mac (Somya-NewMacBook-Air.local)/Desktop/microblog-0.23/app/email.py", line 2, in <module>
    from flask import current_app
ImportError: cannot import name 'current_app' from partially initialized module 'flask' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/suvid/Dropbox/My Mac (Somya-NewMacBook-Air.local)/Desktop/microblog-0.23/app/__init__.py", line 4, in <module>
    from flask import Flask, request, current_app
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/__init__.py", line 16, in <module>
    from werkzeug.exceptions import abort
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/__init__.py", line 220, in <module>
    from .serving import run_simple
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 59, in <module>
    import SocketServer as socketserver
ModuleNotFoundError: No module named 'SocketServer'

**Comment by miguelgrinberg** [comment]
What version of Python are you using?

**Comment by Amazeryogo** [comment]
oh ok

**Comment by Amazeryogo** [comment]
sorry, it was my mistake, I did not run boot.sh  before running the flask app

Sorry, once again.
