### ISSUE TITLE
ImportError: cannot import name 'app'

### ISSUE THREAD

**Issue by WanliangWei** [miguelgrinberg/microblog#26]
Hello,miguel。I have finished your awesome "dog book" three weeks ago, and my code  bases on your  code. The 'app' is created in app/__init__.py, 
     Now I want  to add the full-text search function,but i don't know how to import 'app'.When i tried  to import it directly  like"from app import app", it didn't work and "ImportError: cannot import name 'app'" came out. i have try google and stackoverflow , but there were not helpful answer.
    so i ask you for help. My english is not very well, hope you can understand what i say.Have a nice day!

**Comment by miguelgrinberg** [comment]
Are you using a factory function, like in the book? If you are, then `app` does not exist as a symbol, you only have `create_app`, the function that creates it.

So you need to import `app` from the module that creates it. For example, if you call `create_app` in manage.py, then you can import it from there with `from manage import app`.

**Comment by WanliangWei** [comment]
Actually, l already try that way, but didn't work. This is heroku logs:
`2016-10-21T11:06:11.766503+00:00 app[web.1]: 2016-10-21 11:06:11 [7] [ERROR] Exception in worker process:
2016-10-21T11:06:11.766512+00:00 app[web.1]: Traceback (most recent call last):
2016-10-21T11:06:11.766514+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2016-10-21T11:06:11.766515+00:00 app[web.1]:     worker.init_process()
2016-10-21T11:06:11.766516+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-10-21T11:06:11.766516+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 106, in init_process
2016-10-21T11:06:11.766517+00:00 app[web.1]:     self.callable = self.load()
2016-10-21T11:06:11.766517+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/base.py", line 114, in wsgi
2016-10-21T11:06:11.766520+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2016-10-21T11:06:11.766518+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2016-10-21T11:06:11.766519+00:00 app[web.1]:     return self.load_wsgiapp()
2016-10-21T11:06:11.766521+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/util.py", line 354, in import_app
2016-10-21T11:06:11.766520+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-10-21T11:06:11.766522+00:00 app[web.1]:   File "/app/manage.py", line 19, in <module>
2016-10-21T11:06:11.766522+00:00 app[web.1]:     __import__(module)
2016-10-21T11:06:11.766524+00:00 app[web.1]:     from manage import app
2016-10-21T11:06:11.766523+00:00 app[web.1]:     from app.models import  User, Follow, Role, Permission, Post, Comment, Message, Category, Star, Webpush
2016-10-21T11:06:11.766525+00:00 app[web.1]: ImportError: cannot import name 'app'
2016-10-21T11:06:11.766524+00:00 app[web.1]:   File "/app/app/models.py", line 3, in <module>
2016-10-21T11:06:11.766526+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2016-10-21T11:06:11.766526+00:00 app[web.1]: Traceback (most recent call last):
2016-10-21T11:06:11.766527+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 106, in init_process
2016-10-21T11:06:11.766528+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-10-21T11:06:11.766527+00:00 app[web.1]:     worker.init_process()
2016-10-21T11:06:11.766529+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/base.py", line 114, in wsgi
2016-10-21T11:06:11.766529+00:00 app[web.1]:     self.callable = self.load()
2016-10-21T11:06:11.766531+00:00 app[web.1]:     return self.load_wsgiapp()
2016-10-21T11:06:11.766545+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-10-21T11:06:11.766546+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/util.py", line 354, in import_app
2016-10-21T11:06:11.766547+00:00 app[web.1]:     __import__(module)
2016-10-21T11:06:11.766530+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2016-10-21T11:06:11.766547+00:00 app[web.1]:   File "/app/manage.py", line 19, in <module>
2016-10-21T11:06:11.766531+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2016-10-21T11:06:11.766549+00:00 app[web.1]:     from manage import app
2016-10-21T11:06:11.766548+00:00 app[web.1]:     from app.models import  User, Follow, Role, Permission, Post, Comment, Message, Category, Star, Webpush
2016-10-21T11:06:11.766550+00:00 app[web.1]: ImportError: cannot import name 'app'
2016-10-21T11:06:11.766549+00:00 app[web.1]:   File "/app/app/models.py", line 3, in <module>
2016-10-21T11:06:11.766759+00:00 app[web.1]: 2016-10-21 11:06:11 [7] [INFO] Worker exiting (pid: 7)
2016-10-21T11:06:11.836083+00:00 app[web.1]: 
2016-10-21T11:06:11.836086+00:00 app[web.1]: Error: dictionary changed size during iteration
2016-10-21T11:06:11.836087+00:00 app[web.1]: 
`
This is a part of manage.py : 
`#encoding:utf-8
#!/usr/bin/env python
import os

COV = None
if os.environ.get('FLASK_COVERAGE'):
    import coverage
    COV = coverage.coverage(branch=True, include='app/*')
    COV.start()

if os.path.exists('.env'):
    print('Importing environment from .env...')
    for line in open('.env'):
        var = line.strip().split('=')
        if len(var) == 2:
            os.environ[var[0]] = var[1]

from app import create_app, db
from app.models import  User, Follow, Role, Permission, Post, Comment, Message, Category, Star, Webpush
from app.delete import deletenone
from flask.ext.script import Manager, Shell
from flask.ext.migrate import Migrate, MigrateCommand

app = create_app(os.getenv('FLASK_CONFIG') or 'default')
manager = Manager(app)
migrate = Migrate(app, db, directory="migrations")
`
Even i tried to create a `myapp.py`, create app in this file, then use`from app.myapp import app' in `models.py`, still not working.  I don't know why.

**Comment by miguelgrinberg** [comment]
Your problem is that you have circular dependencies. Some of the imports in manage.py that appear before the `app = create_app()` line issue a `from manage import app`, and that obviously fails.

Move the `from app import create_app` and `app = create_app` lines above your other imports, maybe that'll help.

**Comment by WanliangWei** [comment]
I create app in the models file, then use `from app.models import app` in the manage file. works! Thank you sir.

**Comment by lubingGitHub** [comment]
@WanliangWei   你好，我在学习《Flask Web开发》这本书。现在在往程序里加入文章搜索功能，出现了和你一样的问题。我按照你最后的回复，在models.py里使用app = create_app(),在manage.py使用from app.models import app 。但是出现了其他文件无法引入models.py 中的模型，好像创建实例后，下面的模型就无法被其他文件引用。但是创建语句一定要在Post模型的上面啊。你当时遇到这样的问题了吗？  求帮助！
