### ISSUE TITLE
pymysql error in flask db upgrade

### ISSUE THREAD

**Issue by vinaykumar80** [miguelgrinberg/microblog#282]
Hi @miguelgrinberg ,

Thanks for the blog tutorial!

I am following Chapter 17 (Deployment on Linux) and running into an error, please see the details below. Am I missing anything here?

**.env.sh:**
SECRET_KEY=9abe923769a549cbb1dd1b14b6fb94f2
MAIL_SERVER=localhost
MAIL_PORT=25
DATABASE_URL=mysql+pymysql://microblog:<password>@localhost:3306/microblog
MS_TRANSLATOR_KEY=<your-translator-key-here>

**Executed the below commands:**
$ mysql -u root -p
mysql> create database microblog character set utf8 collate utf8_bin;
mysql> create user 'microblog'@'localhost' identified by '<password>';
mysql> grant all privileges on microblog.* to 'microblog'@'localhost';
mysql> flush privileges;
mysql> quit;

  **(venv) $ flask db upgrade**
 (venv) vagrant@ubuntu-xenial:~/microblog$ flask db upgrade
[2021-01-27 04:50:06,016] INFO in __init__: Microblog startup
Traceback (most recent call last):
  File "/home/vagrant/microblog/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 70, in run_migrations_online
    poolclass=pool.NullPool)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 563, in engine_from_config
    return create_engine(url, **options)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 62, in dbapi
    return __import__("pymysql")
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/pymysql/__init__.py", line 59, in <module>
    from . import connections  # noqa: E402
  File "/home/vagrant/microblog/venv/lib/python3.5/site-packages/pymysql/connections.py", line 206
    ):
    ^
SyntaxError: invalid syntax

**Comment by miguelgrinberg** [comment]
This is an error within the pymysql code. You need to take this to them. Maybe the version of pymysql that you are using is not compatible with your Python 3.5 and you need to use a newer or older release.

**Comment by dreinthebay** [comment]
I had the same error as @vinaykumar80. Here's what I did:
$ pip uninstall pymysql
$ pip install -Iv pymysql==0.9.3

that worked for me. PS @miguelgrinberg thanks for making such a detailed and well-explained tutorial, I've learned so much more than just flask.

**Comment by vinaykumar80** [comment]
Yes, using an older version of pymysql helped me too. Thanks for the blog!

**Comment by LemWong** [comment]
@dreinthebay help me too, thanks!

**Comment by k4o4** [comment]
> I had the same error as @vinaykumar80. Here's what I did:
> $ pip uninstall pymysql
> $ pip install -Iv pymysql==0.9.3
> 
> that worked for me. PS miguelgrinberg thanks for making such a detailed and well-explained tutorial, I've learned so much more than just flask.

Many thanks! It helped

**Comment by miguelgrinberg** [comment]
This is now addressed in the tutorial.
