### ISSUE TITLE
Import order incorrect

### ISSUE THREAD

**Issue by Corfucinas** [miguelgrinberg/microblog#283]
Hi

Currently, the way the import is handled cause that the application will not work with pre-commit tools like `isort`.
For example, in your tutorial, you establish that the __init__.py for /app should be (tag v0.4)

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app import routes, models

```
Using `isort` changes it to

```
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from app import models, routes
from config import Config

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

```

This will break the entire app.

```
flask.cli.NoAppException
flask.cli.NoAppException: While importing "microblog", an ImportError was raised:

Traceback (most recent call last):
  File "/home/the-box/Github/flask-mega-tutorial/.venv/lib/python3.9/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/the-box/Github/flask-mega-tutorial/microblog.py", line 1, in <module>
    from app import app
  File "/home/the-box/Github/flask-mega-tutorial/app/__init__.py", line 5, in <module>
    from app import models, routes
  File "/home/the-box/Github/flask-mega-tutorial/app/models.py", line 2, in <module>
    from app import db
ImportError: cannot import name 'db' from partially initialized module 'app' (most likely due to a circular import) (/home/the-box/Github/flask-mega-tutorial/app/__init__.py)
```

**Comment by miguelgrinberg** [comment]
Yes. Flask is particularly sensitive to circular imports, sometimes the imports need to be carefully designed to avoid this. I suggest you add an exception so that isort does not alter the import order in this file.

**Comment by SamwayneKE** [comment]
I have the same problem. How do we go about it?

**Comment by miguelgrinberg** [comment]
@SamwayneKE I'm not sure I understand what you mean. Not using isort is the solution.

**Comment by SamwayneKE** [comment]
I have an error as above. NoAppException.

Cannot import email from app.emails

**Comment by miguelgrinberg** [comment]
@SamwayneKE I can't really help with the little information you have provided, sorry. This is likely a standard circular dependency error so you have to review your imports.

**Comment by SamwayneKE** [comment]
This is my error!

This is my imports in routes.py

from flask import render_template, flash, redirect, url_for, request
from werkzeug.urls import url_parse
from app import app, db
from app.forms import LoginForm, EditProfileForm, EmptyForm, RegistrationForm, PostForm, ResetPasswordRequestForm
from flask_login import current_user, login_user, logout_user, login_required
from app.models import User, Post
from datetime import datetime
from app.email import send_password_reset_email

flask.cli.NoAppException
flask.cli.NoAppException: While importing "biblechats", an ImportError was raised:

Traceback (most recent call last):
  File "/home/samuel/Desktop/biblechats/venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/samuel/Desktop/biblechats/biblechats.py", line 1, in <module>
    from app import app
  File "/home/samuel/Desktop/biblechats/app/__init__.py", line 52, in <module>
    from app import routes, models, errors
  File "/home/samuel/Desktop/biblechats/app/routes.py", line 8, in <module>
    from app.email import send_password_reset_email
ImportError: cannot import name 'send_password_reset_email' from 'app.email' (/home/samuel/Desktop/biblechats/app/email.py)

Traceback (most recent call last)
File "/home/samuel/Desktop/biblechats/biblechats.py", line 1, in <module>
from app import app
File "/home/samuel/Desktop/biblechats/app/__init__.py", line 52, in <module>
from app import routes, models, errors
File "/home/samuel/Desktop/biblechats/app/routes.py", line 8, in <module>
from app.email import send_password_reset_email
During handling of the above exception, another exception occurred:
File "/home/samuel/Desktop/biblechats/venv/lib/python3.8/site-packages/flask/cli.py", line 343, in __call__
rv = self._load_unlocked()
File "/home/samuel/Desktop/biblechats/venv/lib/python3.8/site-packages/flask/cli.py", line 330, in _load_unlocked
self._app = rv = self.loader()
File "/home/samuel/Desktop/biblechats/venv/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
app = locate_app(self, import_name, name)
File "/home/samuel/Desktop/biblechats/venv/lib/python3.8/site-packages/flask/cli.py", line 245, in locate_app
raise NoAppException(
flask.cli.NoAppException: While importing "biblechats", an ImportError was raised:

Traceback (most recent call last):
File "/home/samuel/Desktop/biblechats/venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
__import__(module_name)
File "/home/samuel/Desktop/biblechats/biblechats.py", line 1, in <module>
from app import app
File "/home/samuel/Desktop/biblechats/app/__init__.py", line 52, in <module>
from app import routes, models, errors
File "/home/samuel/Desktop/biblechats/app/routes.py", line 8, in <module>
from app.email import send_password_reset_email
**ImportError: cannot import name 'send_password_reset_email' from 'app.email'** (/home/samuel/Desktop/biblechats/app/email.py)
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by miguelgrinberg** [comment]
@SamwayneKE so you know how to debug this on your own then?

**Comment by Corfucinas** [comment]
I think you just need to move

'from app import app, db' to the last line of the module, just to make sure that everything else is initialized.

**Comment by SamwayneKE** [comment]
> @SamwayneKE so you know how to debug this on your own then?

Nop still the same error

**Comment by Corfucinas** [comment]
@SamwayneKE it's because you have the import order incorrect (most probably on the __init__.py files), just verify which tag is the corresponding chapter you are in and make sure the imports are in that correct order.

**Comment by samSepol** [comment]
> @SamwayneKE it's because you have the import order incorrect (most probably on the **init**.py files), just verify which tag is the corresponding chapter you are in and make sure the imports are in that correct order.

exactly happens with me in **init.py** file my import order was misplaced so do remember imports order matters in flask

**Comment by maestro0101** [comment]
I have this problem, can anyone help? I'm stuck there.

Traceback (most recent call last):
  File "E:\Pythoshka\Web-site\main.py", line 1, in <module>
    from website import create_app
  File "E:\Pythoshka\Web-site\website\__init__.py", line 1, in <module>
    from website import models
  File "E:\Pythoshka\Web-site\website\models.py", line 2, in <module>
    from . import db
ImportError: cannot import name 'db' from partially initialized module 'website' (most likely due to a circular import)

**Comment by miguelgrinberg** [comment]
I'm closing this issue, since it isn't related to the project. Please look for standard advice dealing with circular dependencies.
