### ISSUE TITLE
Flask-OpenID seems not to be compatible with Python3 despite use of updated package

### ISSUE THREAD

**Issue by ErikBoesen** [miguelgrinberg/microblog#32]
I'm trying to get microblog working in a virtualenv (I've also tried without) on my Mac with El Capitan. I'm attempting to run `python3 db_create.py && python3 db_migrate.py`. I've tried with `Flask-OpenID` versions `1.2.1` and the supposedly Python 3-compatible `1.2.5`, to no avail. Here's my stack trace:

```
/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/six.py:79: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  __import__(name)
/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/filters.py:24: DeprecationWarning: Flags not at the start of the expression \w+(?u)
  _word_re = re.compile(r'\w+(?u)')
Traceback (most recent call last):
  File "db_create.py", line 5, in <module>
    from app import db
  File "/Users/boesene/Desktop/microblog/app/__init__.py", line 6, in <module>
    from flask_openid import OpenID
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/flask_openid.py", line 26, in <module>
    from openid.store.filestore import FileOpenIDStore
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/openid/__init__.py", line 52, in <module>
    if len(version_info) != 3:
TypeError: object of type 'map' has no len()
```

It looks like a pretty simple python3 incompatibility issue, even though I'm using a version of Flask-OpenID which is allegedly compatible with 3.

How could I go about getting around this problem?

**Comment by miguelgrinberg** [comment]
You should be using package python3-openid, not python-openid. I think the requirements in flask-openid should import the correct package, at least that's how it used to work in the past.

**Comment by ErikBoesen** [comment]
Alas, still no success, even when I switch to using `python3-openid`.

**Comment by miguelgrinberg** [comment]
@ErikBoesen this line of code, which appears in your error:

      File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/openid/__init__.py", line 52, in <module>
        if len(version_info) != 3:

does not exist on the python3-openid (the `openid/__init__.py` file has only 46 lines: [link](https://github.com/necaris/python3-openid/blob/a2e6d36f1737c51b71301b24987d1002409b5fc8/openid/__init__.py)). The python-openid package, however, does have it [link](https://github.com/necaris/python-openid/blob/b666238f61574d12f922c40bf7917ec916df7125/openid/__init__.py#L52).

**Comment by ErikBoesen** [comment]
Okay. I scrapped the virtualenv and started from scratch with python3-openid. I now have the following trace:

```python
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/Users/boesene/Desktop/microblog/app/__init__.py", line 6, in <module>
    from flask_openid import OpenID
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/flask_openid.py", line 27, in <module>
    from openid.extensions import ax
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/openid/extensions/ax.py", line 16, in <module>
    from openid.server.trustroot import TrustRoot
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/openid/server/trustroot.py", line 21, in <module>
    from openid.yadis import services
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/openid/yadis/services.py", line 3, in <module>
    from openid.yadis.filters import mkFilter
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/openid/yadis/filters.py", line 14, in <module>
    from openid.yadis.etxrd import expandService
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/openid/yadis/etxrd.py", line 31, in <module>
    SafeElementTree = importSafeElementTree()
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/openid/oidutil.py", line 83, in importSafeElementTree
    return importElementTree(module_names)
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/openid/oidutil.py", line 106, in importElementTree
    ElementTree = __import__(mod_name, None, None, ['unused'])
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/defusedxml/cElementTree.py", line 16, in <module>
    from .ElementTree import DefusedXMLParser, _IterParseIterator
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/defusedxml/ElementTree.py", line 62, in <module>
    _XMLParser, _iterparse, _IterParseIterator, ParseError = _get_py3_cls()
  File "/Users/boesene/Desktop/microblog/venv/lib/python3.6/site-packages/defusedxml/ElementTree.py", line 56, in _get_py3_cls
    _IterParseIterator = pure_pymod._IterParseIterator
AttributeError: module 'xml.etree.ElementTree' has no attribute '_IterParseIterator'
```

From a quick Google search, it seems to relate to [this bug](https://bugs.python.org/issue29050). The developer of defusedxml seems to have fixed the problem, however Flask-OpenID seems to still be relying on an old, unfixed version. Any idea if there is a Flask-OpenID version which works? (I'm trying 1.2.5 at the moment.)

Thank you so much for your help and for your incredibly useful tutorials!

**Comment by miguelgrinberg** [comment]
@ErikBoesen did you try release v0.5.0.rc1 of defusedxml? I think that has the fix.

**Comment by ErikBoesen** [comment]
Switched to a direct GitHub source of defusedxml, and that works now. However, I'm now getting:

```python
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/Users/boesene/Desktop/microblog/app/__init__.py", line 72, in <module>
    from app import views, models
  File "/Users/boesene/Desktop/microblog/app/views.py", line 7, in <module>
    from guess_language import guessLanguage
  File "/Users/boesene/Desktop/microblog/venv/src/guesslanguage/guess_language/__init__.py", line 1, in <module>
    from guess_language import guessLanguage, guessLanguageInfo, guessLanguageName, guessLanguageId
ImportError: cannot import name 'guessLanguage'
```

I tried using a [direct GitHub source](https://bitbucket.org/spirit/guess_language) for `guess_language`, to no avail. I looked through the code and cannot find any reason this should not be working. Any idea what could be the problem here? Pardon my newbie questions :)

**Comment by miguelgrinberg** [comment]
@ErikBoesen This is actually covered in the 15th article of the series: https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xv-ajax. See section "Identifying the language of a post" in that article.

**Comment by ErikBoesen** [comment]
Ah! I must have missed that, my apologies. Thank you so much for your help!

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply anymore.
