### ISSUE TITLE
8.3 Error when running 'flask db migrate'

### ISSUE THREAD

**Issue by sheadscott** [miguelgrinberg/microblog#48]
I got the following error when running 'flask db migrate -m "followers"'
`NameError: name 'followers' is not defined`
I removed the changes to the User class then ran the migration and it works fine so just seems to be an error in the order of operations. 

BTW, thanks for the great update to the tutorial!

**Comment by miguelgrinberg** [comment]
The error message alone does not give me enough context. Do you have the complete stack trace?

**Comment by sheadscott** [comment]
`Traceback (most recent call last):
  File "/Users/Shea/Sites/microblog/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/flask/cli.py", line 256, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/Users/Shea/Sites/microblog/venv/lib/python3.6/site-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/Users/Shea/Sites/microblog/microblog.py", line 1, in <module>
    from app import app, db
  File "/Users/Shea/Sites/microblog/app/__init__.py", line 18, in <module>
    from app import routes, models, errors
  File "/Users/Shea/Sites/microblog/app/routes.py", line 3, in <module>
    from app.forms import LoginForm, RegistrationForm, EditProfileForm
  File "/Users/Shea/Sites/microblog/app/forms.py", line 4, in <module>
    from app.models import User
  File "/Users/Shea/Sites/microblog/app/models.py", line 11, in <module>
    class User(UserMixin, db.Model):
  File "/Users/Shea/Sites/microblog/app/models.py", line 20, in User
    'User', secondary=followers,
NameError: name 'followers' is not defined`

**Comment by miguelgrinberg** [comment]
You are probably missing this: https://github.com/miguelgrinberg/microblog/blob/c4da2aab712bc397c3c437df948505f54fa4329f/app/models.py#L8-L12.

Or maybe you have it, but you put it below line 20, where it is referenced.

**Comment by sheadscott** [comment]
Yes, I had that code below line 20. Thanks!

**Comment by bang98ptit** [comment]
NameError: name 'followers' is not defined, pls help me!

File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
response = self.handle_exception(e)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
raise value
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
response = self.full_dispatch_request()
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
raise value
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/Users/b7ng/microblog/app/routes.py", line 82, in user
return render_template('user.html', user=user, posts=posts)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
context, ctx.app)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
rv = template.render(context)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
return original_render(self, *args, **kwargs)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
Open an interactive python shell in this framereturn self.environment.handle_exception(exc_info, True)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/b7ng/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/Users/b7ng/microblog/app/templates/user.html", line 1, in top-level template code
{% extends "base.html" %}
File "/Users/b7ng/microblog/app/templates/base.html", line 30, in top-level template code
{% block content %}{% endblock %}
File "/Users/b7ng/microblog/app/templates/user.html", line 14, in block "content"
{% elif not current_user.is_following(user) %}
File "/Users/b7ng/microblog/app/models.py", line 55, in is_following
followers.c.followed_id == user.id).count() > 0

**Comment by miguelgrinberg** [comment]
@bang98ptit did you add `followers` above line 55 in models.py, or below? Since it is referenced in line 55, it needs to be added above that line.
