### ISSUE TITLE
question about chapter 4 Database: flask db migrate -m "posts table"

### ISSUE THREAD

**Issue by tianke0711** [miguelgrinberg/microblog#50]
Thanks for your great e-book which I have brought it from your site.
Now I am studying the chapter 4, when run the following command in terminal(mac):
flask db migrate -m "posts table"

there is error:

    (venv) A1706-084:microblog kd$ flask db migrate -m "posts table"
/anaconda3/envs/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/anaconda3/envs/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask_migrate/cli.py", line 90, in migrate
    rev_id, x_arg)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 197, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/command.py", line 176, in revision
    script_directory.run_env()
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/command.py", line 156, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 415, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 427, in _run_environment
    raise util.CommandError("Target database is not up to date.")
alembic.util.exc.CommandError: Target database is not up to date.

Could you tell me how to solve it, thanks!

**Comment by miguelgrinberg** [comment]
I think you forgot to run a `flask db upgrade` command after generating the previous migration. Or else, you generated test migrations that you then decided to not use, but you did not delete the migration script files from the repository.

Basically the error is telling you that the database is configured to match a migration that is not the last. You can find out which migration you are at by running `flask db current`, and you can find the list of migrations you have in your repository with `flask db history`. This should give you a good idea of where the problem is.

**Comment by tianke0711** [comment]
After I delete the migrate by manually, then build it again. the same error. and use the command you mentioned: 


venv) A1706-084:microblog kd$ flask db current
/anaconda3/envs/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

**Comment by tianke0711** [comment]
The whole command and error information as following:


(venv) A1706-084:microblog kd$ flask db init
/anaconda3/envs/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
  Creating directory /Users/kd/microblog/migrations ... done
  Creating directory /Users/kd/microblog/migrations/versions ... done
  Generating /Users/kd/microblog/migrations/alembic.ini ... done
  Generating /Users/kd/microblog/migrations/env.py ... done
  Generating /Users/kd/microblog/migrations/README ... done
  Generating /Users/kd/microblog/migrations/script.py.mako ... done
  Please edit configuration/connection/logging settings in '/Users/kd/microblog/migrations/alembic.ini' before proceeding.
(venv) A1706-084:microblog kd$ flask db migrate -m "users table"
/anaconda3/envs/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'user'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_user_email' on '['email']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_user_username' on '['username']'
INFO  [alembic.autogenerate.compare] Detected added table 'post'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_post_timestamp' on '['timestamp']'
  Generating /Users/k.den/microblog/migrations/versions/eea91da03220_users_table.py ... done
(venv) A1706-084:microblog kd$ flask db upgrade
/anaconda3/envs/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> eea91da03220, users table
(venv) A1706-084:microblog k.den$ flask db migrate -m "posts table"
/anaconda3/envs/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/anaconda3/envs/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask_migrate/cli.py", line 90, in migrate
    rev_id, x_arg)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 197, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/command.py", line 176, in revision
    script_directory.run_env()
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/command.py", line 156, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 415, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 427, in _run_environment
    raise util.CommandError("Target database is not up to date.")
alembic.util.exc.CommandError: Target database is not up to date.
(venv) A1706-084:microblog k.den$ flask db current
/anaconda3/envs/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

**Comment by miguelgrinberg** [comment]
This is troubling: `Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set`.

That means that you have not defined your database. Did you check your configuration?

**Comment by tianke0711** [comment]
@miguelgrinberg  you are right. I wrote the SQLALCHEMY_DATABASE_URI to SQLALCHEMY_DATABASE_URL

**Comment by maheshwariudit7** [comment]
It is showing some strange error. What to do next? Please help
below is the migrate command i have executed after deleting previous versions file. but this error keeps on appearing


(venv) S:\flask-prac>flask db migrate -m "posts table"
Traceback (most recent call last):
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\impl.py", line 239, in _do_get
    return self._create_connection()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect        
    pool.logger.debug("Error on connect(): %s", e)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect        
    connection = pool._invoke_creator(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "S:\flask-prac\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "s:\flask-prac\venv\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "s:\flask-prac\venv\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\flask\cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\flask_migrate\cli.py", line 89, in migrate
    _migrate(directory, message, sql, head, splice, branch_label, version_path,
  File "s:\flask-prac\venv\lib\site-packages\flask_migrate\__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\flask_migrate\__init__.py", line 210, in migrate
    command.revision(config, message, autogenerate=True, sql=sql,
  File "s:\flask-prac\venv\lib\site-packages\alembic\command.py", line 214, in revision
    script_directory.run_env()
  File "s:\flask-prac\venv\lib\site-packages\alembic\script\base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "s:\flask-prac\venv\lib\site-packages\alembic\util\pyfiles.py", line 98, in load_python_file  
    module = load_module_py(module_id, path)
  File "s:\flask-prac\venv\lib\site-packages\alembic\util\compat.py", line 184, in load_module_py    
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations\env.py", line 96, in <module>
    run_migrations_online()
  File "migrations\env.py", line 81, in run_migrations_online
    with connectable.connect() as connection:
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2265, in connect       
    return self._connection_cls(self, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 104, in __init__       
    else engine.raw_connection()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2371, in raw_connection
    return self._wrap_pool_connect(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2341, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\impl.py", line 239, in _do_get
    return self._create_connection()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect        
    pool.logger.debug("Error on connect(): %s", e)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__   
    compat.raise_(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect        
    connection = pool._invoke_creator(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect  
    return dialect.connect(*cargs, **cparams)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\default.py", line 493, in connect     
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)

(venv) S:\flask-prac>flask db migrate -m "posts table"
Traceback (most recent call last):
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\impl.py", line 239, in _do_get
    return self._create_connection()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect        
    pool.logger.debug("Error on connect(): %s", e)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__   
    compat.raise_(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect        
    connection = pool._invoke_creator(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect  
    return dialect.connect(*cargs, **cparams)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "S:\flask-prac\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "s:\flask-prac\venv\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "s:\flask-prac\venv\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\flask\cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\flask_migrate\cli.py", line 89, in migrate
    _migrate(directory, message, sql, head, splice, branch_label, version_path,
  File "s:\flask-prac\venv\lib\site-packages\flask_migrate\__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\flask_migrate\__init__.py", line 210, in migrate        
    command.revision(config, message, autogenerate=True, sql=sql,
  File "s:\flask-prac\venv\lib\site-packages\alembic\command.py", line 214, in revision
    script_directory.run_env()
  File "s:\flask-prac\venv\lib\site-packages\alembic\script\base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "s:\flask-prac\venv\lib\site-packages\alembic\util\pyfiles.py", line 98, in load_python_file  
    module = load_module_py(module_id, path)
  File "s:\flask-prac\venv\lib\site-packages\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations\env.py", line 96, in <module>
    run_migrations_online()
  File "migrations\env.py", line 81, in run_migrations_online
    with connectable.connect() as connection:
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2265, in connect       
    return self._connection_cls(self, **kwargs)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 104, in __init__
    else engine.raw_connection()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2371, in raw_connection
    return self._wrap_pool_connect(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2341, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\impl.py", line 239, in _do_get
    return self._create_connection()
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect        
    pool.logger.debug("Error on connect(): %s", e)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__   
    compat.raise_(
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect        
    connection = pool._invoke_creator(self)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect  
    return dialect.connect(*cargs, **cparams)
  File "s:\flask-prac\venv\lib\site-packages\sqlalchemy\engine\default.py", line 493, in connect     
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by miguelgrinberg** [comment]
The error is "unable to open database file". You need to figure out what happened to your database, it is either corrupted, missing or locked.
