### ISSUE TITLE
Problem with sending email

### ISSUE THREAD

**Issue by Callero** [miguelgrinberg/microblog#62]
I have searched, compared line by line and can't for the life of me figure out what I have done wrong.
Seems the error originates in the email.py file.

```
powershell
127.0.0.1 - - [03/Jan/2018 18:57:27] "GET /reset_password_request HTTP/1.1" 200 -
[2018-01-03 18:57:32,933] ERROR in app: Exception on /reset_password_request [POST]
Traceback (most recent call last):
  File "c:\users\calle\pycharmprojects\flask_megatutorial\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\calle\pycharmprojects\flask_megatutorial\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\calle\pycharmprojects\flask_megatutorial\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\calle\pycharmprojects\flask_megatutorial\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\calle\pycharmprojects\flask_megatutorial\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\calle\pycharmprojects\flask_megatutorial\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Calle\PycharmProjects\flask_megatutorial\app\routes.py", line 160, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Calle\PycharmProjects\flask_megatutorial\app\email.py", line 14, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
127.0.0.1 - - [03/Jan/2018 18:57:34] "POST /reset_password_request HTTP/1.1" 500 -
```

I also tried it in the Flask shell as described in **10.2 Flask-Mail Usage**:

```
powershell
(venv) PS C:\Users\Calle\PycharmProjects\flask_megatutorial> flask shell
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
App: app
Instance: C:\Users\Calle\PycharmProjects\flask_megatutorial\instance
>>> from flask_mail import Message
>>> from app import mail
>>> msg = Message('test subject', sender=app.config['ADMINS'][0],
... recipients=['your-email@example.com'])
>>> msg.body = 'text body'
>>> msg.html = '<h1>HTML body</h1>'
>>> mail.send(msg)
```

Here is the code in  Gist with the files that I suspect:
[https://gist.github.com/Callero/7b7edec02ed1e6be2644b0a3703a1630](https://gist.github.com/Callero/7b7edec02ed1e6be2644b0a3703a1630)

**Comment by Callero** [comment]
I finally found the problem by pushing on in the class.

The issue is that there is no:
`from app import app`
in _app/email.py_ before section **10.8 Asynchronous Emails**, and without that the email function won't work.

Suggest you implement that in section **10.3 A Simple Email Framework**

**Comment by miguelgrinberg** [comment]
> Suggest you implement that in section 10.3 A Simple Email Framework

It's actually needed in section 10.6, this was actually reported a couple of days ago and have added it to that section. The change will appear in the next book update. Thanks!
