### ISSUE TITLE
Problem with flask db upgrade

### ISSUE THREAD

**Issue by bastisawesome** [miguelgrinberg/microblog#75]
While going through the tutorial on deploying to Heroku's cloud I discovered an issue when running the upgrade command through flask db. Output is below:

```
Traceback (most recent call last):
  File "/home/bast/.virtualenvs/microblog/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 23, in <module>
    target_metadata = current_app.extensions['migrate'].db.metadata
AttributeError: 'NoneType' object has no attribute 'metadata'
```
I have tried resetting my virtual environment but to no avail. I skipped the section on using Bootstrap, although having Flask-Bootstrap installed still did nothing to fix the issue. I've been completely unable to fix this error and while this problem persists I will be unable to continue development.

**Comment by miguelgrinberg** [comment]
Did you compare your code against mine? Your `db` variable appears to be `None`, that should be an instance of the `SQLAlchemy` class from the Flask-SQLAlchemy extension.

**Comment by bastisawesome** [comment]
Thanks for helping clear up the error message, I was very confused as to what some of that stuff was saying...

Under App/__init__.py db is declared as type SQLAlchemy.
In microblog.py db is imported from app and returned to the shell.

I've compared those two files to your code and I don't see any problems.

**Comment by miguelgrinberg** [comment]
Can I see your complete `app/__init__.py` module?

**Comment by bastisawesome** [comment]
```
from flask import Flask, current_app, request
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
import logging, os
from logging.handlers import SMTPHandler, RotatingFileHandler
from flask_mail import Mail
from flask_moment import Moment
from flask_babel import Babel, lazy_gettext as _l
from elasticsearch import Elasticsearch

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = _l('Login required to view this page')
moment = Moment()
babel = Babel()

# Configure flask mail
mail = Mail()
def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app)
    login.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    babel.init_app(app)

    app.elasticsearch = Elasticsearch([app.config['ELASTICSEARCH_URL']]) \
        if app.config['ELASTICSEARCH_URL'] else None

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug and not app.testing:
        if app.config['MAIL_SERVER']:
            auth = None
            if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:
                auth = (app.config['MAIL_USERNAME'], app.config['MAIL_PASSWORD'])
            secure = None
            if app.config['MAIL_USE_TLS']:
                secure = ()
            mail_handler = SMTPHandler(
                mailhost=(app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                fromaddr=('no-reply@' + app.config['MAIL_SERVER']),
                toaddrs=app.config['ADMINS'], subject='Microblog Failure',
                credentials=auth, secure=secure)
            mail_handler.setLevel(logging.ERROR)
            app.logger.addHandler(mail_handler)
        
        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/microblog.log', maxBytes=10240,
                                            backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
            app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Microblog startup')

    return app

# Configure current locale
@babel.localeselector
def get_locale():
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])

from app import models
```

I ran the Flask shell and checked the db object, it is created correctly. The website works fine when running through Flask.

**Comment by miguelgrinberg** [comment]
This is wrong:

    migrate.init_app(app)

Should be this:

    migrate.init_app(app, db)

**Comment by bastisawesome** [comment]
Heh, trust me to miss something small yet important (C++ semicolons, anyone?) Thank you so much for your help!

**Comment by dastier** [comment]
> This is wrong:
> 
> ```
> migrate.init_app(app)
> ```
> 
> Should be this:
> 
> ```
> migrate.init_app(app, db)
> ```

Spent an hour to find this answer. It is easy to miss when you work with other extensions like
``` pyton
    bcrypt.init_app(app)
    db.init_app(app)
    ma.init_app(app)
    jwt.init_app(app)
    migrate.init_app(app, db)
```
