### ISSUE TITLE
Notification get_data() crashes with "type object 'Text' has no attribute 'lower'

### ISSUE THREAD

**Issue by bastisawesome** [miguelgrinberg/microblog#77]
So, I've gone through chapter 21 and have hit a snag in my code where I am completely unable to convert Notification.payload_json into string. All errors and code will be listed below. Currently, I have it narrowed down to some sort of issue with the SQLAlchemy type Text. I could be completely wrong, so I will be linking all code snippets that are related to the Notification class below.

```python
class Notification(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), index=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    timestamp = db.Column(db.Float, index=True, default=time)
    payload_json = db.column(db.Text)
    
    def get_data(self):
        return json.loads(str(self.payload_json))
```

> Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 452, in __str__
    return str(self.compile())
  File "<string>", line 1, in <lambda>
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 442, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 448, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 453, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 219, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 716, in visit_column
    name = self.preparer.quote(name)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 3057, in quote
    if self._requires_quotes(ident):
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 3028, in _requires_quotes
    lc_value = value.lower()
AttributeError: type object 'Text' has no attribute 'lower'

```python
def add_notification(self, name, data):
        self.notifications.filter_by(name=name).delete()
        n = Notification(name=name, payload_json=json.dumps(data), user=self)
        db.session.add(n)
        return n
```

``` python
def messages():
    current_user.last_message_read_time = datetime.utcnow()
    current_user.add_notification('unread_message_count', 0)
    db.session.commit()
```

```python
def notifications():
    since = request.args.get('since', 0.0, type=float)
    notifications = current_user.notifications.filter(
        Notification.timestamp > since).order_by(Notification.timestamp.asc())
    return jsonify([{
        'name': n.name,
        'data': n.get_data(),
        'timestamp': n.timestamp
        } for n in notifications])
```

```html
<script>
        {% if current_user.is_authenticated %}
        $(function() {
            var since = 0;
            setInterval(function() {
                $.ajax('{{ url_for('main.notifications') }}?since=' + since).done(
                    function(notifications) {
                        for(var i=0; i<notifications.length; i++) {
                            if(notifications[i].name == 'unread_message_count')
                                set_message_count(notifications[i].data);
                            since = notifications[i].timestamp;
                        }
                    }
                );
            }, 10000);
        });
        {% endif %}
    </script>
```

**Comment by miguelgrinberg** [comment]
Are you sure the stack trace that you included is complete? I don't see any reference to the microblog code, so I have no idea what instruction from the application caused this error. Please check if your stack trace is longer, or maybe has more stack traces chained after or before this one.

**Comment by bastisawesome** [comment]
That was the stack trace I received from running the shell and trying to narrow down where it is coming from.

> 127.0.0.1 - - [30/Jan/2018 21:21:46] "GET /notifications?since=0 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bast/microblog/app/main/routes.py", line 209, in notifications
    } for n in notifications])
  File "/home/bast/microblog/app/main/routes.py", line 209, in <listcomp>
    } for n in notifications])
  File "/home/bast/microblog/app/models.py", line 163, in get_data
    return json.loads(str(self.payload_json))
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 452, in __str__
    return str(self.compile())
  File "<string>", line 1, in <lambda>
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 442, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 448, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 453, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 219, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 716, in visit_column
    name = self.preparer.quote(name)
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 3057, in quote
    if self._requires_quotes(ident):
  File "/home/bast/.virtualenvs/microblog/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 3028, in _requires_quotes
    lc_value = value.lower()
AttributeError: type object 'Text' has no attribute 'lower'

**Comment by bastisawesome** [comment]
So, I was messing around in the Flask shell to try to figure out exactly where the error is (and verifying that it is on trying to convert payload_json to String) and I started noticing some weird behaviours. If I add a new notification to a user object then immediately print the payload_json variable it will output the JSON string. However, if I run the exact same piece of code then I get the object definitions.

> <sqlalchemy.sql.elements.ColumnClause at 0x7f71eb250fd0; <class 'sqlalchemy.sql.sqltypes.Text'>>

I'm not really sure what is going on here.

**Comment by miguelgrinberg** [comment]
If you can send me a snippet of code or a complete script I can use to reproduce this error I can debug this for you. With the information that you provided I unfortunately don't see where the problem is.

**Comment by bastisawesome** [comment]
I'm afraid I still haven't figured out where the problem is. I've only managed to figure out that the first time I call payload_json it outputs the proper value and every subsequent call outputs the aforementioned information to the screen. Any related code snippets have already been written in the original issue comment.

Right now all I'm doing is trying to access the information manually in the interactive shell by calling 

> u.notifications[1].payload_json

That's all of the information I can give as far as I'm aware.

**Comment by bastisawesome** [comment]
Update: it turns out I used the wrong capitalisation on the column and had written db.column instead of db.Column. So, this was, as I suspected at first, a complete oversight in my code.

**Comment by bastisawesome** [comment]
Update: it turns out I used the wrong capitalisation on the column and had written db.column instead of db.Column. So, this was, as I suspected at first, a complete oversight in my code.
